-- =====================================================================
-- Como se regenera db/ (2026-09-05). Tres consultas de solo lectura a pg_catalog; cada una
-- devuelve UN texto que se guarda tal cual como archivo. Verificar funciones con
--   select proname, md5(pg_get_functiondef(oid)) from pg_proc where pronamespace = '"GP2"'::regnamespace
-- contra el md5 de cada bloque del archivo (bloque = pg_get_functiondef + ';' + salto de linea).
-- =====================================================================

-- ---------- 1) tablas_GP2.sql ----------
with t as (
  select c.oid, c.relname
    from pg_class c
   where c.relnamespace = '"GP2"'::regnamespace and c.relkind = 'r'
),
cols as (
  select t.relname,
         string_agg(
           '  ' || a.attname || ' ' || format_type(a.atttypid, a.atttypmod)
           || case when a.attidentity = 'd' then ' generated by default as identity'
                   when a.attidentity = 'a' then ' generated always as identity' else '' end
           || case when a.attnotnull then ' not null' else '' end
           || case when ad.adbin is not null then ' default ' || pg_get_expr(ad.adbin, ad.adrelid) else '' end,
           E',\n' order by a.attnum) as cols
    from t
    join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
    left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
   group by t.relname
),
cons as (
  select t.relname,
         string_agg('  constraint ' || con.conname || ' ' || pg_get_constraintdef(con.oid), E',\n'
                    order by case con.contype when 'p' then 0 when 'u' then 1 when 'f' then 2 else 3 end, con.conname) as cons
    from t join pg_constraint con on con.conrelid = t.oid
   group by t.relname
),
comentarios as (
  select t.relname,
         string_agg('comment on ' || case when d.objsubid = 0 then 'table "GP2".' || t.relname
                                          else 'column "GP2".' || t.relname || '.' || a.attname end
                    || ' is ' || quote_literal(d.description) || ';', E'\n' order by d.objsubid) as com
    from t
    join pg_description d on d.objoid = t.oid and d.classoid = 'pg_class'::regclass
    left join pg_attribute a on a.attrelid = t.oid and a.attnum = d.objsubid and d.objsubid > 0
   group by t.relname
),
tablas as (
  select string_agg(
           '-- ---------- ' || t.relname || ' ----------' || E'\n'
           || 'create table "GP2".' || t.relname || ' (' || E'\n'
           || cols.cols
           || coalesce(E',\n' || cons.cons, '') || E'\n);'
           || coalesce(E'\n' || comentarios.com, ''),
           E'\n\n' order by t.relname) as txt
    from t join cols using (relname) left join cons using (relname) left join comentarios using (relname)
),
idx as (
  select string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by ic.relname) as txt
    from t join pg_index i on i.indrelid = t.oid
    join pg_class ic on ic.oid = i.indexrelid
   where not exists (select 1 from pg_constraint con where con.conindid = i.indexrelid)
),
trg as (
  select string_agg(pg_get_triggerdef(tg.oid) || ';', E'\n\n' order by t.relname, tg.tgname) as txt
    from t join pg_trigger tg on tg.tgrelid = t.oid and not tg.tgisinternal
),
rls as (
  select string_agg('alter table "GP2".' || t.relname || ' enable row level security;', E'\n' order by t.relname) as txt
    from t join pg_class c on c.oid = t.oid where c.relrowsecurity
),
pol as (
  select string_agg('create policy ' || p.policyname || ' on "GP2".' || p.tablename
                    || ' for ' || lower(p.cmd) || ' to ' || array_to_string(p.roles, ', ')
                    || coalesce(' using (' || p.qual || ')', '')
                    || coalesce(' with check (' || p.with_check || ')', '') || ';', E'\n' order by p.tablename, p.policyname) as txt
    from pg_policies p where p.schemaname = 'GP2'
),
stats as (
  select (select count(*) from t) n_t,
         (select count(*) from t join pg_constraint con on con.conrelid = t.oid) n_c,
         (select count(*) from t join pg_index i on i.indrelid = t.oid where not exists (select 1 from pg_constraint con where con.conindid = i.indexrelid)) n_i,
         (select count(*) from t join pg_trigger tg on tg.tgrelid = t.oid and not tg.tgisinternal) n_tg,
         (select count(*) from t join pg_class c on c.oid = t.oid where c.relrowsecurity) n_rls,
         (select count(*) from pg_policies p where p.schemaname = 'GP2') n_pol
)
select '-- =====================================================================' || E'\n'
    || '-- TABLAS del schema GP2 (DDL reconstruido de pg_catalog: columnas, identity, defaults, constraints, comentarios) — export automatico 2026-09-05 desde Supabase (hrxfctzncixxqmpfhskv)' || E'\n'
    || '-- Respaldo/referencia. La fuente de verdad es la base; regenerar al cambiar el schema.' || E'\n'
    || '-- ' || stats.n_t || ' tablas, ' || stats.n_c || ' constraints, ' || stats.n_i || ' indices sueltos, ' || stats.n_tg || ' triggers, RLS en ' || stats.n_rls || ' tablas, ' || stats.n_pol || ' policies.' || E'\n'
    || '-- =====================================================================' || E'\n\n'
    || tablas.txt || E'\n\n'
    || '-- ============ INDICES (no asociados a constraints) ============' || E'\n\n' || coalesce(idx.txt, '') || E'\n\n'
    || '-- ============ TRIGGERS ============' || E'\n\n' || coalesce(trg.txt, '') || E'\n\n'
    || '-- ============ ROW LEVEL SECURITY ============' || E'\n\n' || coalesce(rls.txt, '') || E'\n\n'
    || '-- ============ POLICIES ============' || E'\n'
    || '-- Todas son de SELECT: ninguna tabla GP2 acepta escritura anonima directa (la escritura va por RPC SECURITY DEFINER).' || E'\n\n'
    || coalesce(pol.txt, '') || E'\n' as archivo
from tablas, idx, trg, rls, pol, stats;

-- ---------- 2) funciones_GP2.sql ----------
select '-- =====================================================================' || E'\n'
    || '-- FUNCIONES del schema GP2 — export automatico <FECHA> (pg_get_functiondef, exacto)' || E'\n'
    || '-- Fuente de verdad: Supabase (hrxfctzncixxqmpfhskv). Este archivo es respaldo/referencia.' || E'\n'
    || '-- ' || count(*) || ' funciones. Los GRANT/REVOKE no estan aca: EXECUTE para anon solo en las RPC de pantalla (ver db/README.md).' || E'\n'
    || '-- =====================================================================' || E'\n\n'
    || string_agg('-- ---------- ' || proname || ' ----------' || E'\n' || pg_get_functiondef(oid) || ';' || E'\n', E'\n' order by proname) as archivo
from pg_proc where pronamespace = '"GP2"'::regnamespace;

-- ---------- 3) vistas_GP2.sql ----------
select '-- =====================================================================' || E'\n'
    || '-- VISTAS del schema GP2 (pg_get_viewdef, exacto) — export automatico <FECHA> desde Supabase (hrxfctzncixxqmpfhskv)' || E'\n'
    || '-- Respaldo/referencia. La fuente de verdad es la base; regenerar al cambiar el schema.' || E'\n'
    || '-- ' || count(*) || ' vistas. Orden de creacion: las que dependen de otra van despues.' || E'\n'
    || '-- =====================================================================' || E'\n\n'
    || string_agg('-- ---------- ' || c.relname || ' ----------' || E'\n'
                  || 'create or replace view "GP2".' || c.relname || ' as' || E'\n' || pg_get_viewdef(c.oid, true)
                  || coalesce(E'\n' || 'comment on view "GP2".' || c.relname || ' is ' || quote_literal(d.description) || ';', '') || E'\n',
                  E'\n' order by c.relname) as archivo
from pg_class c left join pg_description d on d.objoid = c.oid and d.objsubid = 0
where c.relnamespace = '"GP2"'::regnamespace and c.relkind = 'v';
