-- =====================================================================
-- TABLAS del schema GP2 (DDL reconstruido de pg_catalog: columnas, identity, defaults, constraints, comentarios) — export automatico 2026-09-11 desde Supabase (hrxfctzncixxqmpfhskv)
-- Respaldo/referencia. La fuente de verdad es la base; regenerar al cambiar el schema.
-- 51 tablas, 181 constraints, 61 indices sueltos, 14 triggers, RLS en 51 tablas, 51 policies.
-- =====================================================================

-- ---------- __sim_base ----------
create table "GP2".__sim_base (
  comp bigint,
  ubic bigint,
  cantidad numeric
);
comment on table "GP2".__sim_base is 'TEMPORAL (auditoria de rutas 2026-09-11): linea de base del inventario para el arnes __sim_ruta. Se llena y se revierte dentro de la misma transaccion; fuera de una corrida esta vacia. Borrar al cerrar la auditoria.';

-- ---------- articulo ----------
create table "GP2".articulo (
  id bigint generated by default as identity not null,
  codigo text not null,
  familia text,
  componente_caja_id bigint,
  articulos_por_caja integer,
  discontinuado boolean not null default false,
  descripcion text,
  marca text,
  constraint articulo_pkey PRIMARY KEY (id),
  constraint articulo_codigo_key UNIQUE (codigo),
  constraint articulo_componente_caja_id_fkey FOREIGN KEY (componente_caja_id) REFERENCES "GP2".componente(id),
  constraint articulo_familia_fkey FOREIGN KEY (familia) REFERENCES "GP2".familia(nombre) ON UPDATE CASCADE,
  constraint articulo_marca_chk CHECK (((marca IS NULL) OR (marca = ANY (ARRAY['LOEKE'::text, 'LOKE'::text, 'CHEF'::text]))))
);
comment on table "GP2".articulo is 'Articulo terminado (codigo de venta) con familia, caja y unidades por caja. Receta en articulo_componente; ruta en ruta/ruta_paso.';
comment on column "GP2".articulo.discontinuado is 'true = ya no se fabrica (ej. 119 y 809: ahora se importan — ver sufijo E en CONOCIMIENTO). Sin fila activa en Est Madre no generan consumo; el flag es para que las pantallas los distingan.';

-- ---------- articulo_componente ----------
create table "GP2".articulo_componente (
  id bigint generated by default as identity not null,
  articulo_id bigint not null,
  componente_id bigint not null,
  cantidad numeric not null,
  constraint articulo_componente_pkey PRIMARY KEY (id),
  constraint articulo_componente_articulo_id_fkey FOREIGN KEY (articulo_id) REFERENCES "GP2".articulo(id),
  constraint articulo_componente_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id)
);
comment on table "GP2".articulo_componente is 'Receta directa del articulo: que componentes lleva y cuantos por unidad. La escribe abm_bom_guardar.';

-- ---------- articulo_prov_at ----------
create table "GP2".articulo_prov_at (
  id bigint not null default nextval('"GP2".articulo_prov_at_id_seq'::regclass),
  proveedor_at_id bigint not null,
  cod_art text not null,
  descripcion text,
  activo boolean not null default true,
  n_caja integer,
  marca text,
  creado_en timestamp with time zone not null default now(),
  constraint articulo_prov_at_pkey PRIMARY KEY (id),
  constraint articulo_prov_at_proveedor_at_id_cod_art_key UNIQUE (proveedor_at_id, cod_art),
  constraint articulo_prov_at_proveedor_at_id_fkey FOREIGN KEY (proveedor_at_id) REFERENCES "GP2".proveedor_at(id)
);
comment on table "GP2".articulo_prov_at is 'Catalogo de articulos que fabrica cada proveedor de articulo terminado (cod_art, caja, marca).';
comment on column "GP2".articulo_prov_at.descripcion is 'Como llama el PROVEEDOR a este articulo, que es lo que va impreso en su remito. NO tiene por que coincidir con articulo.descripcion y hoy difiere en 52 de las filas que cruzan por codigo. La descripcion canonica de GP2 es articulo.descripcion; esta es el rotulo del proveedor. crear_entrega_prov_at cae a articulo.descripcion y despues al cod_art cuando esta vacia.';
-- ---------- carton_categoria ----------
create table "GP2".carton_categoria (
  nombre text not null,
  formato text not null,
  mezcla_libre boolean not null default false,
  constraint carton_categoria_pkey PRIMARY KEY (nombre),
  constraint carton_categoria_formato_fkey FOREIGN KEY (formato) REFERENCES "GP2".carton_formato(nombre)
);
comment on table "GP2".carton_categoria is 'Familias de pedido del carton tipo C. mezcla_libre = se puede sumar a cualquier otra familia para completar el multiplo (hoy solo Sacacorchos). Pisapapas quedo sin uso: no existe esa familia de articulo.';

-- ---------- carton_formato ----------
create table "GP2".carton_formato (
  nombre text not null,
  pliegos_multiplo integer not null,
  codigo_multiplo integer not null,
  min_codigo_x_multiplo integer not null,
  nota text,
  uni_x_bolsa integer,
  paq_x_bolsa integer,
  pedido_minimo numeric,
  constraint carton_formato_pkey PRIMARY KEY (nombre)
);
comment on table "GP2".carton_formato is 'Formatos de carton y su regla de envase (multiplo de compra, pedido minimo, uni x bolsa, paquetes x bolsa) para la OC y el control de recepcion (REGLAS_OC_INSUMOS.md).';
comment on column "GP2".carton_formato.uni_x_bolsa is 'Unidades por bolsa: cuantos codigos entran en una bolsa envasada. Huevo=2000, 8=3000, C=1000, LOKE=1000. NULL para Pliego/Bolsa (formatos que no van embolsados por codigos).';
comment on column "GP2".carton_formato.pedido_minimo is 'Pedido minimo de la familia, en unidades. Distinto del multiplo: el multiplo dice de a cuanto sube el total, el minimo dice el piso para que el proveedor lo tome. NULL = sin piso.';

-- ---------- componente ----------
create table "GP2".componente (
  id bigint generated by default as identity not null,
  codigo text,
  descripcion text,
  sector_id bigint not null,
  unidad_medida text not null,
  kg_x_uni numeric,
  uni_x_cajon numeric,
  proveedor text,
  carton_formato text,
  carton_categoria text,
  estado_compra text,
  marca text,
  es_pliego boolean not null default false,
  recibe_en_cajas boolean not null default false,
  relev_solo_sueltas boolean not null default false,
  material_id bigint,
  codigo_isis_ch text,
  codigo_virgilio text,
  pedido_minimo_uni numeric,
  mb_color text,
  constraint componente_pkey PRIMARY KEY (id),
  constraint componente_carton_categoria_fkey FOREIGN KEY (carton_categoria) REFERENCES "GP2".carton_categoria(nombre),
  constraint componente_carton_formato_fkey FOREIGN KEY (carton_formato) REFERENCES "GP2".carton_formato(nombre),
  constraint componente_material_id_fkey FOREIGN KEY (material_id) REFERENCES "GP2".componente(id),
  constraint componente_proveedor_fkey FOREIGN KEY (proveedor) REFERENCES "GP2".proveedor_insumo(nombre) ON UPDATE CASCADE ON DELETE SET NULL,
  constraint componente_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES "GP2".sector(id),
  constraint componente_estado_compra_chk CHECK (((estado_compra IS NULL) OR (estado_compra = ANY (ARRAY['fabricacion'::text, 'discontinuo'::text, 'importado'::text, 'compra'::text])))),
  constraint componente_mb_color_chk CHECK (((mb_color IS NULL) OR (mb_color = ANY (ARRAY['R'::text, 'B'::text, 'A'::text, 'N'::text])))),
  constraint componente_marca_chk CHECK (((marca IS NULL) OR (marca = ANY (ARRAY['LOEKE'::text, 'CHEF'::text])))),
  constraint componente_unidad_medida_chk CHECK ((unidad_medida = ANY (ARRAY['kg'::text, 'unidad'::text])))
);
comment on table "GP2".componente is 'Maestro de piezas e insumos: codigo, sector, unidad, kg/uni, uni x cajon, proveedor, estado de compra. Un codigo puede repetirse en OTRO sector (A1 pieza / A1 caja): la clave es id.';
comment on column "GP2".componente.estado_compra is 'null = se compra; fabricacion = se hace adentro; discontinuo = ya no se usa. Los que tienen estado quedan fuera de la OC y no cuentan como "sin proveedor".';
comment on column "GP2".componente.recibe_en_cajas is 'El proveedor lo entrega en cajas que se PESAN: la recepcion va siempre en kg (sin toggle) y el control se carga como cajas x kg por caja. No cambia la unidad_medida canonica del componente.';
comment on column "GP2".componente.relev_solo_sueltas is 'true = en el relevamiento se cuenta SOLO por unidades sueltas, sin envase (no aplica cajon/bolsa/paquete).';
comment on column "GP2".componente.material_id is 'Materia prima (componente del Sector Materia Prima Plastica, en kg) con la que se inyecta esta pieza. kg consumidos por unidad = kg_x_uni x (1 + parametro inyeccion_desperdicio_pct/100). Lo descuenta crear_recepcion_insumo del stock del inyector al recepcionar. null = no se sabe / no aplica (no se inventa).';
comment on column "GP2".componente.codigo_isis_ch is 'Cod ISIS con el que CHEF SRL identifica el mismo material (la OC de materia prima lleva un renglon LK con codigo y otro CH con este). null = Chef no lo tiene codificado. Hoy solo materia prima plastica (2026-09-11).';
comment on column "GP2".componente.codigo_virgilio is 'Codigo del mismo insumo en el catalogo Insumos de Gestion Virgilio (bolsas: PP, ABS, AI, NV, NR, N25, PE, PS). 2026-09-11.';
comment on column "GP2".componente.pedido_minimo_uni is 'Pedido minimo del proveedor para ESA pieza, en unidades. Sale de la columna "Pedi Min Uni" de la hoja "Pedido 31-08" del Excel de plasticos del usuario (cargado 2026-09-11). Se aplica DESPUES del maximo: la OC nunca pide menos que esto (o pide 0).';

comment on column "GP2".componente.unidad_medida is 'Unidad canonica de la pieza: ''kg'' o ''unidad'' (CHECK). OJO: movimiento.unidad_origen/destino, orden_compra_item.unidad y recepcion_insumo.unidad usan ''uni'', NO ''unidad''; fn_movimiento_calc traduce. El que compare esta columna contra ''uni'' no matchea nunca y cae al camino de kg. No unificar sin tocar las dos puntas.';
comment on column "GP2".componente.mb_color is 'Color de Master Bach que lleva esta pieza plastica: R rojo, B blanco, A azul, N negro. Origen: columna MB de la hoja "Consumo x Cod Articulo" del Excel de plasticos del usuario (40 de 47 partes con consumo la traen; las 7 sin color son las de Nylon recuperado, que viene pigmentado, mas B2 y EP9). null = todavia no se cargo -- no se inventa. recalcular_maximo_material() suma el 4% por color cuando esta cargado y cae al prorrateo cuando no.';
-- ---------- componente_bom ----------
create table "GP2".componente_bom (
  id bigint generated by default as identity not null,
  componente_padre_id bigint,
  componente_hijo_id bigint,
  cantidad numeric,
  constraint componente_bom_pkey PRIMARY KEY (id),
  constraint componente_bom_componente_hijo_id_fkey FOREIGN KEY (componente_hijo_id) REFERENCES "GP2".componente(id),
  constraint componente_bom_componente_padre_id_fkey FOREIGN KEY (componente_padre_id) REFERENCES "GP2".componente(id)
);
comment on table "GP2".componente_bom is 'Receta de un componente armado (intermedio): que componentes consume y cuantos.';

-- ---------- contraparte_alias ----------
create table "GP2".contraparte_alias (
  alias text not null,
  tipo text not null,
  ref_id bigint,
  constraint contraparte_alias_pkey PRIMARY KEY (alias),
  constraint contraparte_alias_tipo_check CHECK ((tipo = ANY (ARRAY['tallerista'::text, 'proveedor_at'::text, 'proveedor_servicio'::text, 'interno'::text]))),
  constraint contraparte_alias_upper_chk CHECK ((alias = upper(alias)))
);
comment on table "GP2".contraparte_alias is 'Alias (siempre en mayusculas) con que planillas y espejos nombran a una contraparte (tipo + ref_id), para cruzar por texto.';

-- ---------- empleado ----------
create table "GP2".empleado (
  id bigint generated always as identity not null,
  legajo text not null,
  nombre text not null,
  activo boolean not null default true,
  tipo text,
  hora_entrada time without time zone,
  constraint empleado_pkey PRIMARY KEY (id),
  constraint empleado_legajo_key UNIQUE (legajo),
  constraint empleado_tipo_chk CHECK (((tipo IS NULL) OR (tipo = ANY (ARRAY['operario'::text, 'administrativo'::text]))))
);
comment on table "GP2".empleado is 'Operarios de la fabrica (legajo, nombre, tipo, hora de entrada, activo) para la app de produccion. La escriben empleado_guardar / empleado_activar.';

-- ---------- entrega_prov_at ----------
create table "GP2".entrega_prov_at (
  id bigint not null default nextval('"GP2".entrega_prov_at_id_seq'::regclass),
  proveedor_at_id bigint,
  cod_art text,
  descripcion text,
  cantidad_cajas integer not null,
  remito text,
  dia_mes text,
  tipo_entrega text,
  fecha_rto date,
  numero_factura text,
  fecha_factura date,
  creado_en timestamp with time zone not null default now(),
  constraint entrega_prov_at_pkey PRIMARY KEY (id),
  constraint entrega_prov_at_articulo_fkey FOREIGN KEY (proveedor_at_id, cod_art) REFERENCES "GP2".articulo_prov_at(proveedor_at_id, cod_art) ON UPDATE CASCADE,
  constraint entrega_prov_at_proveedor_at_id_fkey FOREIGN KEY (proveedor_at_id) REFERENCES "GP2".proveedor_at(id),
  constraint entrega_prov_at_tipo_entrega_chk CHECK ((tipo_entrega = ANY (ARRAY['factura'::text, 'remito_factura'::text])))
);
comment on table "GP2".entrega_prov_at is 'Entregas de articulo terminado de los Prov AT (cajas por cod_art, remito, factura). Es un segundo ledger fuera de movimiento (pregunta 22).';

comment on column "GP2".entrega_prov_at.descripcion is 'SNAPSHOT de la descripcion del remito al momento de la entrega. Hoy coincide en las 0 divergencias con articulo_prov_at, pero es a proposito una copia: el remito ya emitido no cambia si despues se corrige el catalogo.';
-- ---------- est_madre ----------
create table "GP2".est_madre (
  cod text not null,
  proy_cajas_mes numeric,
  uxb integer,
  proy_uni_mes numeric,
  actualizado timestamp with time zone,
  copiado_en timestamp with time zone not null default now(),
  constraint proyeccion_venta_pkey PRIMARY KEY (cod)
);
comment on table "GP2".est_madre is 'Espejo de la Estadistica Madre (public.proyeccion_madre, trigger fn_est_madre_sync): unidades por mes de cada articulo; alimenta minimos y maximos.';

-- ---------- faltante_marcado ----------
create table "GP2".faltante_marcado (
  id bigint generated always as identity not null,
  componente_id bigint not null,
  origen text not null,
  nota text,
  marcado_por text,
  creado_en timestamp with time zone not null default now(),
  resuelto_en timestamp with time zone,
  constraint faltante_marcado_pkey PRIMARY KEY (id),
  constraint faltante_marcado_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint faltante_marcado_origen_check CHECK ((origen = ANY (ARRAY['envios_tall'::text, 'envios_ps'::text, 'operario'::text, 'manual'::text])))
);
comment on table "GP2".faltante_marcado is 'Faltantes marcados a mano (componente, origen, nota, quien) hasta que se resuelven (resuelto_en).';

-- ---------- familia ----------
create table "GP2".familia (
  id bigint generated by default as identity not null,
  nombre text not null,
  constraint familia_pkey PRIMARY KEY (id),
  constraint familia_nombre_key UNIQUE (nombre)
);
comment on table "GP2".familia is 'Familias de articulos (nombre unico).';

-- ---------- fleje_detalle ----------
create table "GP2".fleje_detalle (
  componente_id bigint not null,
  n_fleje text,
  medida_mm text,
  cons_mensual numeric,
  kg_x_cajon numeric,
  cod_isis text,
  actualizado_en timestamp with time zone default now(),
  kg_uni_desp numeric,
  descripcion_parte text,
  constraint fleje_detalle_pkey PRIMARY KEY (componente_id),
  constraint fleje_detalle_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id) ON DELETE CASCADE
);
comment on table "GP2".fleje_detalle is 'Datos propios de cada fleje (n° de fleje, medida, codigo ISIS, kg por unidad despiece, consumo mensual, kg x cajon); una fila por componente de Sector Fleje.';
comment on column "GP2".fleje_detalle.descripcion_parte is 'NO es una copia de componente.descripcion: es la PARTE que sale de ese fleje, otro dato. Difiere en las 52 filas y esta bien.';
-- ---------- inventario ----------
create table "GP2".inventario (
  id bigint not null default nextval('"GP2".inventario_id_seq'::regclass),
  componente_id bigint not null,
  ubicacion_id bigint not null,
  cantidad numeric default 0,
  minimo numeric default 0,
  actualizado_en timestamp with time zone,
  maximo numeric,
  maximo_origen text,
  cajones_x_ubicacion numeric,
  ubicaciones integer,
  minimo_origen text,
  constraint inventario_pkey PRIMARY KEY (id),
  constraint inventario_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint inventario_ubicacion_id_fkey FOREIGN KEY (ubicacion_id) REFERENCES "GP2".ubicacion(id),
  constraint inventario_maximo_origen_chk CHECK ((maximo_origen = ANY (ARRAY['cinco_cajones'::text, 'est_madre'::text, 'fisico'::text, 'faat_reserva_lote'::text, 'mb_4pct_por_color'::text]))),
  constraint inventario_minimo_origen_chk CHECK ((minimo_origen = ANY (ARRAY['consumo'::text, 'excel_uni_convertido_kg'::text])))
);
comment on table "GP2".inventario is 'Stock por componente y ubicacion (cantidad canonica, minimo, maximo y su origen). La cantidad la escriben SOLO los triggers de movimiento; minimo/maximo, las RPC de recalculo.';
comment on column "GP2".inventario.maximo is 'Maximo de este componente en esta ubicacion. Crudo/Procesado: lo pone fn_recalc_maximos_cajones = max_cajones_x_ubicacion (parametro, hoy 5) x componente.uni_x_cajon. Insumos: fn_recalc_maximos_insumos, por Est Madre explotada x meses_stock. OJO: las columnas componente.cajones_x_ubicacion y componente.ubicaciones NO entran en la cuenta (la migracion del 2026-08-30 que las usaba quedo revertida: pregunta 5 de PREGUNTAS_ARQUITECTURA_GP2.md, sin responder).';
comment on column "GP2".inventario.cajones_x_ubicacion is 'Cajones que entran en UNA ubicacion fisica. Origen: SC Kg."Max Caj Cerv" / SP Kg."Max Cajon SP Cerv". NO LA LEE NADIE (0 funciones, 0 vistas, 0 pantallas): quedo de la migracion de maximos del 2026-08-30, que el trigger fn_recalc_maximos_cajones revirtio. Ver el comment de inventario.maximo y la pregunta 5 de PREGUNTAS_ARQUITECTURA_GP2.md, sin responder.';
comment on column "GP2".inventario.ubicaciones is 'Ubicaciones fisicas consecutivas que ocupa el sector. Solo se nombra la primera, asi que se deduce como (numero del proximo codigo de la misma letra) - (numero propio). Minimo 1. NO LA LEE NADIE, igual que cajones_x_ubicacion: ver el comment de esa columna.';
comment on column "GP2".inventario.minimo_origen is 'null = carga original del usuario (Excel); consumo = lo calculo recalcular_minimos (que SI pisa las filas con origen null cuando el consumo es > 0; solo respeta consumo 0/desconocido); excel_uni_convertido_kg = conversion de la carga original.';

comment on column "GP2".inventario.maximo_origen is 'De donde salio el maximo de esta fila. Vocabulario CERRADO por inventario_maximo_origen_chk: est_madre, cinco_cajones, fisico, faat_reserva_lote, mb_4pct_por_color (mas null = sin maximo cargado). Lo escriben los triggers de recalculo; oc_bundle lo muestra para explicar el sugerido. El valor mb_2pct_del_plastico existio hasta el 2026-09-12, cuando el usuario fijo el master en 4 % y por color.';
-- ---------- matriz ----------
create table "GP2".matriz (
  id bigint generated by default as identity not null,
  n_matriz text not null,
  descripcion text,
  tipo text,
  partes_por_kilo_de_fleje numeric,
  tiempo_historico numeric,
  uni_x_golpe numeric not null default 1,
  tiempo_unidad text not null default 'uni'::text,
  maquina text,
  activa boolean not null default true,
  constraint matriz_pkey PRIMARY KEY (id),
  constraint matriz_n_matriz_key UNIQUE (n_matriz),
  constraint matriz_maquina_chk CHECK (((maquina IS NULL) OR (maquina = ANY (ARRAY['alimentador'::text, 'balancin'::text, 'piedra'::text])))),
  constraint matriz_tiempo_unidad_chk CHECK ((tiempo_unidad = ANY (ARRAY['uni'::text, 'kg'::text]))),
  constraint matriz_tipo_chk CHECK (((tipo IS NULL) OR (tipo = ANY (ARRAY['A'::text, 'B'::text, 'D'::text, 'P'::text])))),
  constraint matriz_uni_x_golpe_positivo CHECK ((uni_x_golpe > (0)::numeric))
);
comment on table "GP2".matriz is 'Matrices de la fabrica (n°, descripcion, tiempo historico, uni x golpe, piezas por kg de fleje).';
comment on column "GP2".matriz.uni_x_golpe is 'Unidades que salen por cada golpe del contador de la matriz (alimentador o balancin). El operario anota GOLPES; las unidades producidas = golpes * uni_x_golpe. Fuente inicial: Conteo_Gral_FLEJES_y_Alambre.xls, hoja Consumo KG x Art, columna "Uni x Golpe" (2026-08-31).';
comment on column "GP2".matriz.tiempo_unidad is 'En que se mide tiempo_historico: "uni" = segundos por pieza (el caso normal, verificado contra db_n8n_espejo) o "kg" = segundos por kilo procesado. La 501 (afilado de cuchillas) es por kg [usuario 2026-08-31].';
comment on column "GP2".matriz.maquina is 'Donde se produce: alimentador (un golpe por segundo) o balancin (6 a 10 s minimo). Mapeo del usuario 2026-08-31: A=alimentador, B y D=balancin, P=piedra (501, se mide por kg). Sirve para leer bien un tiempo: no se compara un tiempo de alimentador con uno de balancin.';
comment on column "GP2".matriz.activa is 'false = la matriz existe pero hoy no se usa. Las apps no la ofrecen para elegir; se sigue leyendo para la historia.';

-- ---------- movimiento ----------
create table "GP2".movimiento (
  id bigint not null default nextval('"GP2".movimiento_id_seq'::regclass),
  fecha timestamp with time zone not null,
  tipo_mov text not null,
  comp_id bigint not null,
  ubic_origen_id bigint,
  ubic_destino_id bigint,
  cantidad numeric not null,
  comp_transformado_id bigint,
  cantidad_transformada numeric,
  unidad_origen text,
  unidad_destino text,
  _delta_orig numeric,
  _delta_dest numeric,
  cajones numeric,
  faltante boolean not null default false,
  nota text,
  constraint movimiento_pkey PRIMARY KEY (id),
  constraint movimiento_comp_id_fkey FOREIGN KEY (comp_id) REFERENCES "GP2".componente(id),
  constraint movimiento_comp_transformado_id_fkey FOREIGN KEY (comp_transformado_id) REFERENCES "GP2".componente(id),
  constraint movimiento_tipo_mov_fk FOREIGN KEY (tipo_mov) REFERENCES "GP2".tipo_movimiento(clave) ON UPDATE CASCADE,
  constraint movimiento_ubic_destino_id_fkey FOREIGN KEY (ubic_destino_id) REFERENCES "GP2".ubicacion(id),
  constraint movimiento_ubic_origen_id_fkey FOREIGN KEY (ubic_origen_id) REFERENCES "GP2".ubicacion(id),
  constraint movimiento_tiene_lado_chk CHECK (((ubic_origen_id IS NOT NULL) OR (ubic_destino_id IS NOT NULL))),
  constraint movimiento_unidad_destino_chk CHECK (((unidad_destino IS NULL) OR (unidad_destino = ANY (ARRAY['kg'::text, 'uni'::text])))),
  constraint movimiento_unidad_origen_chk CHECK (((unidad_origen IS NULL) OR (unidad_origen = ANY (ARRAY['kg'::text, 'uni'::text]))))
);
comment on table "GP2".movimiento is 'El libro (ledger) de stock: cada fila es un evento con tipo_mov del vocabulario cerrado (CHECK). Los triggers calculan _delta_orig/_delta_dest y los aplican en inventario. Solo se escribe por RPC.';
comment on column "GP2".movimiento.unidad_origen is 'Unidad en que vino la cantidad del origen: kg o uni (vocabulario cerrado, CHECK; el trigger fn_movimiento_calc normaliza unidad/pliego/KG a uni/kg antes de calcular). null = la misma que unidad_destino.';
comment on column "GP2".movimiento.unidad_destino is 'Unidad de la cantidad del destino (cantidad_transformada cuando hay comp_transformado_id): kg o uni (vocabulario cerrado, CHECK). null = la misma que unidad_origen.';
comment on column "GP2".movimiento._delta_orig is 'delta canonico restado al ORIGEN (congelado al aplicar; usado para revertir sin drift)';
comment on column "GP2".movimiento._delta_dest is 'delta canonico sumado al DESTINO (congelado al aplicar)';
comment on column "GP2".movimiento.cajones is 'Conteo fisico de cajones del movimiento. Independiente de cantidad (peso/unidades). kg/cajones = carga real del cajon.';
comment on column "GP2".movimiento.faltante is 'Columna F: el operario marco que la parte no se pudo completar en este envio.';
comment on column "GP2".movimiento.nota is 'Texto libre del operario (motivo de una devolucion, aclaracion de un ajuste). Antes vivia en devolucion_tallerista.motivo (tabla borrada 2026-09-05).';

-- ---------- orden_compra ----------
create table "GP2".orden_compra (
  id bigint generated by default as identity not null,
  numero integer not null,
  proveedor text,
  rubro text,
  estado text not null default 'borrador'::text,
  nota text,
  creado_en timestamp with time zone not null default now(),
  creado_por text,
  fecha_entrega_estimada date,
  constraint orden_compra_pkey PRIMARY KEY (id),
  constraint orden_compra_proveedor_fkey FOREIGN KEY (proveedor) REFERENCES "GP2".proveedor_insumo(nombre) ON UPDATE CASCADE,
  constraint orden_compra_estado_check CHECK ((estado = ANY (ARRAY['borrador'::text, 'enviada'::text, 'recibida'::text, 'anulada'::text])))
);
comment on table "GP2".orden_compra is 'Ordenes de compra de insumos por proveedor y rubro (borrador -> enviada -> recibida / anulada). Las crea crear_oc; la recepcion las cruza (recibido).';
comment on column "GP2".orden_compra.fecha_entrega_estimada is 'Fecha de entrega estimada de esta OC, la que se imprime en la hoja que va al proveedor. Se propone desde proveedor_insumo.dias_entrega pero es editable y se guarda por OC (el proveedor puede confirmar otra). NULL = sin fecha acordada.';

comment on column "GP2".orden_compra.rubro is 'ETIQUETA de la pantalla, no sector.nombre: OC_GP2.html le saca el prefijo "Sector " a proposito (nombreRubro). Por eso NO tiene FK contra sector. El rubro real sale del sector del componente.';
-- ---------- orden_compra_item ----------
create table "GP2".orden_compra_item (
  id bigint generated by default as identity not null,
  oc_id bigint not null,
  componente_id bigint not null,
  cantidad numeric not null,
  unidad text not null default 'uni'::text,
  recibido numeric not null default 0,
  precio_uni numeric,
  moneda text,
  constraint orden_compra_item_pkey PRIMARY KEY (id),
  constraint orden_compra_item_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint orden_compra_item_oc_id_fkey FOREIGN KEY (oc_id) REFERENCES "GP2".orden_compra(id) ON DELETE CASCADE,
  constraint orden_compra_item_cantidad_check CHECK ((cantidad > (0)::numeric)),
  constraint orden_compra_item_moneda_chk CHECK ((moneda = ANY (ARRAY['ARS'::text, 'USD'::text]))),
  constraint orden_compra_item_unidad_chk CHECK ((unidad = ANY (ARRAY['kg'::text, 'uni'::text])))
);
comment on table "GP2".orden_compra_item is 'Renglones de la OC: componente, cantidad pedida, unidad, recibido (lo va llenando la recepcion), precio.';
comment on column "GP2".orden_compra_item.unidad is 'kg o uni (CHECK). Charcas se pide en paquetes (charcas_kg_x_paquete kg) y crear_oc lo guarda en kg.';

-- ---------- parametro ----------
create table "GP2".parametro (
  clave text not null,
  valor numeric not null,
  descripcion text,
  constraint parametro_pkey PRIMARY KEY (clave)
);
comment on table "GP2".parametro is 'Parametros con nombre (clave/valor), p.ej. max_cajones_x_ubicacion = 5 y caja_uni_x_paquete.';

comment on column "GP2".parametro.clave is 'Clave del parametro. master_bach_pct = cuanto master lleva la pieza sobre sus kg de resina, APARTE (usuario 2026-09-12: "x kg de bolsas plasticas y tambien el 4% de masterback").';
-- ---------- parte_proveedor_servicio ----------
create table "GP2".parte_proveedor_servicio (
  componente_id bigint not null,
  proveedor_servicio_id bigint not null,
  creado_en timestamp with time zone not null default now(),
  asignado boolean not null default false,
  constraint parte_proveedor_servicio_pkey PRIMARY KEY (componente_id, proveedor_servicio_id),
  constraint parte_proveedor_servicio_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id) ON DELETE CASCADE,
  constraint parte_proveedor_servicio_proveedor_servicio_id_fkey FOREIGN KEY (proveedor_servicio_id) REFERENCES "GP2".proveedor_servicio(id) ON DELETE CASCADE
);
comment on table "GP2".parte_proveedor_servicio is 'Que piezas pinta/procesa cada proveedor de servicio (asignacion de pintores) y cual es el asignado activo.';

-- ---------- planilla_fila ----------
create table "GP2".planilla_fila (
  id bigint not null default nextval('"GP2".planilla_fila_id_seq'::regclass),
  snapshot_id integer not null,
  hoja text not null,
  fila integer not null,
  bloque text,
  datos jsonb not null,
  formulas jsonb,
  constraint planilla_fila_pkey PRIMARY KEY (id),
  constraint planilla_fila_uk UNIQUE (snapshot_id, hoja, fila),
  constraint planilla_fila_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES "GP2".planilla_snapshot(id) ON DELETE CASCADE
);
comment on table "GP2".planilla_fila is 'Filas crudas de la planilla madre. datos = celdas por letra de columna; formulas = la formula cruda donde se guardo.';

-- ---------- planilla_snapshot ----------
create table "GP2".planilla_snapshot (
  id integer not null default nextval('"GP2".planilla_snapshot_id_seq'::regclass),
  archivo text not null,
  subido_en timestamp with time zone not null default now(),
  subido_por text,
  nota text,
  vigente boolean not null default true,
  constraint planilla_snapshot_pkey PRIMARY KEY (id)
);
comment on table "GP2".planilla_snapshot is 'Cada subida de la planilla madre de costos (A_Costos_VIGENTES.xlsx). vigente=true es la ultima.';

-- ---------- precio_proveedor ----------
create table "GP2".precio_proveedor (
  id bigint generated by default as identity not null,
  rubro text,
  cod_prov text,
  producto text not null,
  precio numeric,
  moneda text,
  fecha_lista date,
  componente_id bigint,
  copiado_en timestamp with time zone default now(),
  precio_por_kg boolean not null default false,
  constraint precio_proveedor_pkey PRIMARY KEY (id),
  constraint precio_proveedor_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint precio_proveedor_moneda_chk CHECK ((moneda = ANY (ARRAY['ARS'::text, 'USD'::text])))
);
comment on table "GP2".precio_proveedor is 'Precios de compra de insumos por proveedor y componente (lista, moneda, fecha, precio por kg).';
comment on column "GP2".precio_proveedor.precio_por_kg is 'true = el precio es por KG: la vista de costos lo multiplica por componente.kg_x_uni en vivo (regla del usuario: el peso vive en el componente, la tarifa en el proveedor)';

comment on column "GP2".precio_proveedor.rubro is 'Rubro TAL COMO VIENE de la planilla del usuario (17 grafias distintas). NO es sector.nombre y no lo lee ninguna funcion ni vista: es referencia de la carga. El rubro real del componente sale de sector / sector.oc_rubro_id.';
-- ---------- precio_servicio_pieza ----------
create table "GP2".precio_servicio_pieza (
  id bigint generated always as identity not null,
  proveedor_servicio_id bigint not null,
  componente_id bigint not null,
  precio_uni numeric,
  moneda text not null default 'ARS'::text,
  origen text,
  actualizado_en timestamp with time zone not null default now(),
  proceso text,
  precio_kg numeric,
  constraint precio_servicio_pieza_pkey PRIMARY KEY (id),
  constraint precio_servicio_pieza_proveedor_servicio_id_componente_id_key UNIQUE (proveedor_servicio_id, componente_id),
  constraint precio_servicio_pieza_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint precio_servicio_pieza_proceso_fkey FOREIGN KEY (proceso) REFERENCES "GP2".proceso(nombre) ON UPDATE CASCADE,
  constraint precio_servicio_pieza_proveedor_servicio_id_fkey FOREIGN KEY (proveedor_servicio_id) REFERENCES "GP2".proveedor_servicio(id),
  constraint precio_servicio_pieza_moneda_chk CHECK ((moneda = ANY (ARRAY['ARS'::text, 'USD'::text])))
);
comment on table "GP2".precio_servicio_pieza is 'Precio del servicio de un PS POR PIEZA (126 filas; 36 sin precio_uni ni precio_kg, que son las que se rellenan con tarifa_servicio). Es la MISMA entidad que tarifa_servicio a otra granularidad. No la nombra ninguna funcion, solo v_costo_componente.';
comment on column "GP2".precio_servicio_pieza.precio_kg is 'tarifa $/kg del proceso; la vista multiplica por el kg_x_uni VIVO de la pieza. Si esta, gana sobre precio_uni';

-- ---------- precio_tallerista ----------
create table "GP2".precio_tallerista (
  id bigint generated always as identity not null,
  tallerista_id bigint not null,
  componente_id bigint not null,
  concepto text,
  precio_uni numeric not null,
  moneda text not null default 'ARS'::text,
  referencia text,
  actualizado_en timestamp with time zone not null default now(),
  precio_kg numeric,
  constraint precio_tallerista_pkey PRIMARY KEY (id),
  constraint precio_tallerista_tallerista_id_componente_id_key UNIQUE (tallerista_id, componente_id),
  constraint precio_tallerista_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint precio_tallerista_tallerista_id_fkey FOREIGN KEY (tallerista_id) REFERENCES "GP2".tallerista(id),
  constraint precio_tallerista_moneda_chk CHECK ((moneda = ANY (ARRAY['ARS'::text, 'USD'::text])))
);
comment on table "GP2".precio_tallerista is 'Tarifa del tallerista por pieza/articulo (concepto descriptivo, precio; el precio por kg lo deriva el trigger fn_precio_tallerista_kg).';
comment on column "GP2".precio_tallerista.precio_kg is 'Tarifa POR KILO cuando el tallerista cobra asi. Es el dato de origen; el trigger trg_precio_tallerista_kg calcula precio_uni = precio_kg x componente.kg_x_uni, que es lo que lee v_costo_componente. Si se carga solo precio_uni, esta columna queda null y no pasa nada.';

-- ---------- proceso ----------
create table "GP2".proceso (
  nombre text not null,
  descripcion text,
  constraint proceso_pkey PRIMARY KEY (nombre)
);
comment on table "GP2".proceso is 'Catalogo de procesos de servicio (pintado, calado, cromado, ...).';

-- ---------- produccion ----------
create table "GP2".produccion (
  id bigint not null default nextval('"GP2".produccion_id_seq'::regclass),
  fecha timestamp with time zone,
  legajo text,
  nombre_empleado text,
  matriz_raw text,
  nombre_matriz text,
  matriz_id bigint,
  uni real,
  premio double precision,
  tiempo_toma real,
  tiempo_historico real,
  hora_inicio time without time zone,
  hora_fin time without time zone,
  anular_tiempo boolean,
  segundos_historico numeric,
  segundos_trabajados numeric,
  segundos_tiempo_muerto numeric,
  dia integer,
  mes integer,
  quincena integer,
  id_ejecucion text,
  eliminar text,
  revisado boolean,
  origen_created_at timestamp with time zone,
  golpes numeric,
  uni_x_golpe numeric,
  constraint produccion_pkey PRIMARY KEY (id),
  constraint produccion_legajo_fkey FOREIGN KEY (legajo) REFERENCES "GP2".empleado(legajo) ON UPDATE CASCADE,
  constraint produccion_matriz_id_fkey FOREIGN KEY (matriz_id) REFERENCES "GP2".matriz(id)
);
comment on table "GP2".produccion is 'Registros de produccion de la app de operarios (legajo, matriz, unidades/golpes, horas, premio). Soft delete con eliminar = S. Los escriben registrar_evento_prod / registrar_produccion.';
comment on column "GP2".produccion.nombre_empleado is 'SNAPSHOT del nombre del empleado al momento de la produccion, igual que nombre_matriz. No es un espejo de empleado.nombre.';
comment on column "GP2".produccion.nombre_matriz is 'SNAPSHOT del nombre de la matriz al momento de la produccion, no un espejo de matriz.descripcion: si la matriz se renombra, lo ya producido sigue diciendo como se llamaba entonces. Hoy difiere en 2 de 13 filas y eso es correcto.';
comment on column "GP2".produccion.golpes is 'Golpes que marco el contador de la matriz. NULL = el registro vino en unidades directas (app vieja).';
comment on column "GP2".produccion.uni_x_golpe is 'Foto del matriz.uni_x_golpe usado para pasar golpes -> uni en este registro.';

-- ---------- proveedor_at ----------
create table "GP2".proveedor_at (
  id bigint generated always as identity not null,
  cod_prov text,
  nombre text not null,
  activo boolean not null default true,
  notas text,
  constraint proveedor_at_pkey PRIMARY KEY (id),
  constraint proveedor_at_nombre_key UNIQUE (nombre)
);
comment on table "GP2".proveedor_at is 'Proveedores de articulo terminado (nos venden producto armado). Cada uno tiene su ubicacion de stock.';

-- ---------- proveedor_insumo ----------
create table "GP2".proveedor_insumo (
  nombre text not null,
  informa_rollos boolean not null default false,
  activo boolean not null default true,
  factura_uni boolean not null default false,
  modo_control text not null default 'ninguno'::text,
  rubro text,
  cod_prov text,
  dias_entrega integer,
  id bigint generated by default as identity not null,
  entrega_en text,
  pedido_minimo_kg numeric,
  constraint proveedor_insumo_pkey PRIMARY KEY (nombre),
  constraint proveedor_insumo_id_uk UNIQUE (id),
  constraint proveedor_insumo_rubro_fkey FOREIGN KEY (rubro) REFERENCES "GP2".sector(nombre) ON UPDATE CASCADE,
  constraint proveedor_insumo_modo_control_chk CHECK ((modo_control = ANY (ARRAY['ninguno'::text, 'rollos_remito'::text, 'pesaje'::text, 'peso_total'::text, 'pendiente'::text])))
);
comment on table "GP2".proveedor_insumo is 'Proveedores de insumos (rubro, modo de control de la recepcion: rollos_remito / pesaje / peso_total / ninguno).';
comment on column "GP2".proveedor_insumo.rubro is 'Sector al que va la botonera de este proveedor. Es sector.nombre COMPLETO ("Sector Bombilla", no "Bombillas") y tiene FK desde el 2026-09-11: inyectores_bundle lo compara por texto.';
comment on column "GP2".proveedor_insumo.cod_prov is 'Código de proveedor en ISIS (contable). Se muestra en el módulo de Recepción unificada para el checklist del sector Pagos.';
comment on column "GP2".proveedor_insumo.dias_entrega is 'Dias tipicos de entrega de este proveedor (plazo desde que se le manda la OC hasta que entrega). Se usa para PROPONER orden_compra.fecha_entrega_estimada = fecha de la OC + dias_entrega. NULL = todavia no se sabe (no se inventa): la pantalla no propone fecha y el usuario la escribe a mano.';
comment on column "GP2".proveedor_insumo.id is 'Id numerico (2026-09-10) para que una ubicacion pueda referenciar al proveedor: los INYECTORES tienen ubicacion tipo inyector con ref_id = este id (stock de materia prima en su poder). La PK sigue siendo nombre.';
comment on column "GP2".proveedor_insumo.entrega_en is 'Direccion de entrega que va en la hoja de OC. NULL = la del rubro (material plastico: Virgilio 2788). Master Bach: Cervantes 2868 "por ahora" (usuario 2026-09-11).';
comment on column "GP2".proveedor_insumo.pedido_minimo_kg is 'Cuanto es lo minimo que ese proveedor vende en una OC (kg). Del Excel del usuario, hoja Relev y OP Bolsas Plast. 2026-09-11.';

-- ---------- proveedor_servicio ----------
create table "GP2".proveedor_servicio (
  id bigint generated by default as identity not null,
  cod_prov text,
  nombre text,
  proceso text,
  hibrido boolean not null default false,
  nombre_corto text,
  mp_componente_id bigint,
  desperdicio_pct numeric not null default 0,
  constraint proveedor_servicio_pkey PRIMARY KEY (id),
  constraint proveedor_servicio_mp_componente_id_fkey FOREIGN KEY (mp_componente_id) REFERENCES "GP2".componente(id)
);
comment on table "GP2".proveedor_servicio is 'Proveedores de servicio (PS): proceso, nombre corto para pantallas, hibrido (tambien compra materia prima: mp_componente_id). Cada uno tiene su ubicacion (la crea alta_proveedor_servicio).';
comment on column "GP2".proveedor_servicio.nombre_corto is 'Como lo llaman en la planta (Jade, Ximpa, Scor, FAAT). Antes: proveedor_servicio_alias.nombre_viejo (tabla borrada 2026-09-05).';
comment on column "GP2".proveedor_servicio.mp_componente_id is 'PS hibrido: la materia prima BRUTA que recibe y consume (Charcas -> FLEJE90_BRUTO, Eclipse -> CHAPA430). Quien la vende es componente.proveedor. Lo usa cargar_compra_mp (2026-09-05).';
comment on column "GP2".proveedor_servicio.desperdicio_pct is 'PS hibrido: % de desperdicio al procesar nuestra materia prima (mp_componente_id). crear_oc lo usa para la OC gemela al proveedor de la MP (kg de producto x (1 + pct/100)) y cargar_recepcion_eclipse para descontar la chapa. Eclipse 28 (calibrado con remito, usuario 2026-09-02). Charcas 0 (usuario 2026-09-04: sin dato, asumir 0; la recepcion descuenta 1:1). Antes: parametro charcas_/eclipse_desperdicio_pct.';

comment on column "GP2".proveedor_servicio.proceso is 'ROTULO libre en Title Case, SIN FK contra el catalogo proceso (14 de 15 filas quedan fuera). En 7 de los 8 lectores es solo texto de pantalla, pero pintores_bundle lo usa como LOGICA: desde el 2026-09-11 compara lower(btrim(proceso)) = ''pintado'', asi que da igual como este escrito. La relacion real PS<->proceso, que es 1:N (FAAT hace temple y cementado, Guazzaroni niquelado, pulido y zincado), vive normalizada en tarifa_servicio y precio_servicio_pieza. No "limpiar" esta columna sin mirar pintores_bundle.';
-- ---------- recepcion_control ----------
create table "GP2".recepcion_control (
  id bigint generated always as identity not null,
  recepcion_id bigint not null,
  peso_balanza numeric not null,
  controlado_por text,
  controlado_en timestamp with time zone not null default now(),
  nota text,
  nro_pallet integer not null default 1,
  constraint recepcion_control_pkey PRIMARY KEY (id),
  constraint recepcion_control_pallet_uk UNIQUE (recepcion_id, nro_pallet),
  constraint recepcion_control_recepcion_id_fkey FOREIGN KEY (recepcion_id) REFERENCES "GP2".recepcion_insumo(id) ON DELETE CASCADE,
  constraint recepcion_control_peso_balanza_check CHECK ((peso_balanza > (0)::numeric))
);
comment on table "GP2".recepcion_control is 'Una fila por PALLET pesado. peso_balanza es lo que marca la balanza para ese pallet, con la tara del pallet incluida.';

-- ---------- recepcion_control_rollo ----------
create table "GP2".recepcion_control_rollo (
  id bigint generated always as identity not null,
  control_id bigint not null,
  cantidad integer not null,
  kg_por_rollo numeric not null,
  constraint recepcion_control_rollo_pkey PRIMARY KEY (id),
  constraint recepcion_control_rollo_control_id_fkey FOREIGN KEY (control_id) REFERENCES "GP2".recepcion_control(id) ON DELETE CASCADE,
  constraint recepcion_control_rollo_cantidad_check CHECK ((cantidad > 0)),
  constraint recepcion_control_rollo_kg_por_rollo_check CHECK ((kg_por_rollo > (0)::numeric))
);
comment on table "GP2".recepcion_control_rollo is 'Rollos declarados al pesar un pallet (cantidad, kg por rollo); el trigger fn_rollo_desde_control da de alta el rollo.';

-- ---------- recepcion_insumo ----------
create table "GP2".recepcion_insumo (
  id bigint not null default nextval('"GP2".recepcion_insumo_id_seq'::regclass),
  fecha timestamp with time zone not null default now(),
  componente_id bigint not null,
  proveedor text,
  remito text,
  cantidad numeric not null,
  unidad text not null default 'uni'::text,
  movimiento_id bigint,
  created_at timestamp with time zone default now(),
  rollos integer,
  pallets integer,
  controlado boolean not null default false,
  cantidad_declarada numeric,
  base integer,
  pisos integer,
  sueltas integer,
  paquetes integer,
  uni_x_paq integer,
  controlado_en timestamp with time zone,
  controlado_por text,
  rollos_json jsonb,
  constraint recepcion_insumo_pkey PRIMARY KEY (id),
  constraint recepcion_insumo_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint recepcion_insumo_movimiento_id_fkey FOREIGN KEY (movimiento_id) REFERENCES "GP2".movimiento(id) ON DELETE SET NULL,
  constraint recepcion_insumo_proveedor_fkey FOREIGN KEY (proveedor) REFERENCES "GP2".proveedor_insumo(nombre) ON UPDATE CASCADE,
  constraint recepcion_insumo_pallets_check CHECK (((pallets IS NULL) OR (pallets > 0))),
  constraint recepcion_insumo_unidad_chk CHECK ((unidad = ANY (ARRAY['kg'::text, 'uni'::text])))
);
comment on table "GP2".recepcion_insumo is 'Recepciones de insumos: componente, proveedor, remito, cantidad declarada y controlada, movimiento asociado, rollos/pallets. Cruza contra las OC abiertas (_aplicar_recepcion_a_oc).';
comment on column "GP2".recepcion_insumo.rollos is 'Cantidad de rollos declarada en el remito. Solo la informan algunos proveedores (Aperam, Basconia). Null = el remito no la trae.';
comment on column "GP2".recepcion_insumo.pallets is 'Cantidad de pallets que llegaron, anotada en la carga junto con los kg y los rollos del remito. Cada pallet se pesa por separado en el control.';
comment on column "GP2".recepcion_insumo.controlado is 'true = ya se hizo el control fisico (base x pisos + sueltas para cajas)';
comment on column "GP2".recepcion_insumo.cantidad_declarada is 'cantidad segun remito del proveedor; se guarda al hacer control para poder comparar declarado vs real';

-- ---------- relevamiento ----------
create table "GP2".relevamiento (
  id bigint not null default nextval('"GP2".relevamiento_id_seq'::regclass),
  sector_id bigint not null,
  fecha date not null default CURRENT_DATE,
  encargado text,
  estado text not null default 'en_curso'::text,
  cronograma_id bigint,
  creado_en timestamp with time zone not null default now(),
  cerrado_en timestamp with time zone,
  aplicado_en timestamp with time zone,
  constraint relevamiento_pkey PRIMARY KEY (id),
  constraint relevamiento_cronograma_id_fkey FOREIGN KEY (cronograma_id) REFERENCES "GP2".relevamiento_cronograma(id),
  constraint relevamiento_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES "GP2".sector(id),
  constraint relevamiento_estado_ck CHECK ((estado = ANY (ARRAY['en_curso'::text, 'contado'::text, 'aplicado'::text, 'anulado'::text])))
);
comment on table "GP2".relevamiento is 'Conteo fisico de un sector (en_curso -> contado -> aplicado), con encargado, cronograma y fechas.';

-- ---------- relevamiento_cronograma ----------
create table "GP2".relevamiento_cronograma (
  id bigint not null default nextval('"GP2".relevamiento_cronograma_id_seq'::regclass),
  tipo text not null,
  sector_id bigint,
  fecha date not null,
  nota text,
  creado_en timestamp with time zone not null default now(),
  constraint relevamiento_cronograma_pkey PRIMARY KEY (id),
  constraint relevamiento_cronograma_tipo_fecha_key UNIQUE (tipo, fecha),
  constraint relevamiento_cronograma_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES "GP2".sector(id)
);
comment on table "GP2".relevamiento_cronograma is 'Fechas programadas de conteo por tipo. Origen: Excel "conteo" del usuario (2026-09-04).';
comment on column "GP2".relevamiento_cronograma.sector_id is 'Sector GP2 que se cuenta. NULL cuando el tipo del Excel todavia no tiene sector (caso "Bolsa Plast").';

comment on column "GP2".relevamiento_cronograma.tipo is 'ROTULO del Excel "conteo" del usuario (Bombillas, Cartones, Garage, ...). Es 1:1 con sector_id salvo "Bolsa Plást", que todavia no tiene sector. El sector real es sector_id: no cruzar por este texto. Es el tercer juego de nombres para los mismos sectores (sector.nombre, proveedor_insumo.rubro, este).';
-- ---------- relevamiento_item ----------
create table "GP2".relevamiento_item (
  id bigint not null default nextval('"GP2".relevamiento_item_id_seq'::regclass),
  relevamiento_id bigint not null,
  componente_id bigint not null,
  envases numeric,
  sueltas numeric,
  kg numeric,
  total_uni numeric,
  stock_programa numeric,
  decision text,
  contado boolean not null default false,
  constraint relevamiento_item_pkey PRIMARY KEY (id),
  constraint relevamiento_item_relevamiento_id_componente_id_key UNIQUE (relevamiento_id, componente_id),
  constraint relevamiento_item_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint relevamiento_item_relevamiento_id_fkey FOREIGN KEY (relevamiento_id) REFERENCES "GP2".relevamiento(id) ON DELETE CASCADE,
  constraint relevamiento_item_decision_ck CHECK ((decision = ANY (ARRAY['conteo'::text, 'programa'::text])))
);
comment on table "GP2".relevamiento_item is 'Renglones del conteo: envases, sueltas, kg, total en unidades, stock del programa al momento y la decision (conteo / programa).';

-- ---------- rollo_evento ----------
create table "GP2".rollo_evento (
  id bigint generated always as identity not null,
  fecha timestamp with time zone not null default now(),
  componente_id bigint not null,
  kg_por_rollo numeric not null,
  delta integer not null,
  motivo text not null,
  legajo text,
  control_rollo_id bigint,
  nota text,
  constraint rollo_evento_pkey PRIMARY KEY (id),
  constraint rollo_evento_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint rollo_evento_control_rollo_id_fkey FOREIGN KEY (control_rollo_id) REFERENCES "GP2".recepcion_control_rollo(id) ON DELETE SET NULL,
  constraint rollo_evento_legajo_fkey FOREIGN KEY (legajo) REFERENCES "GP2".empleado(legajo) ON UPDATE CASCADE,
  constraint rollo_evento_delta_check CHECK ((delta <> 0)),
  constraint rollo_evento_kg_por_rollo_check CHECK ((kg_por_rollo > (0)::numeric)),
  constraint rollo_evento_motivo_check CHECK ((motivo = ANY (ARRAY['inicial'::text, 'recepcion'::text, 'toma_operario'::text, 'ajuste'::text, 'devolucion'::text])))
);
comment on table "GP2".rollo_evento is 'Eventos de rollos de fleje (alta desde el control, ajustes, tomas): componente, kg por rollo, delta, motivo, legajo.';

-- ---------- rollo_uso ----------
create table "GP2".rollo_uso (
  id bigint generated always as identity not null,
  legajo text not null,
  componente_id bigint not null,
  kg_por_rollo numeric not null,
  matriz_raw text,
  ts_inicio timestamp with time zone not null default now(),
  ts_fin timestamp with time zone,
  quedo_resto boolean,
  uni_producidas numeric,
  uni_esperadas numeric,
  rollo_evento_id bigint,
  constraint rollo_uso_pkey PRIMARY KEY (id),
  constraint rollo_uso_componente_id_fkey FOREIGN KEY (componente_id) REFERENCES "GP2".componente(id),
  constraint rollo_uso_legajo_fkey FOREIGN KEY (legajo) REFERENCES "GP2".empleado(legajo) ON UPDATE CASCADE,
  constraint rollo_uso_rollo_evento_id_fkey FOREIGN KEY (rollo_evento_id) REFERENCES "GP2".rollo_evento(id)
);
comment on table "GP2".rollo_uso is 'Uso de un rollo por un operario (legajo, matriz, inicio/fin, quedo resto, unidades producidas vs esperadas).';

-- ---------- ruta ----------
create table "GP2".ruta (
  id bigint generated by default as identity not null,
  nombre text,
  articulo_id bigint,
  constraint ruta_pkey PRIMARY KEY (id),
  constraint ruta_articulo_id_fkey FOREIGN KEY (articulo_id) REFERENCES "GP2".articulo(id)
);
comment on table "GP2".ruta is 'Ruta productiva de un articulo (una por tallerista cuando mas de uno hace el mismo paso). Sus pasos en ruta_paso.';

-- ---------- ruta_paso ----------
create table "GP2".ruta_paso (
  id bigint generated by default as identity not null,
  ruta_id bigint not null,
  orden integer not null,
  tipo_paso text not null,
  matriz_id bigint,
  proveedor_id bigint,
  tallerista_id bigint,
  comp_entrada_id bigint,
  comp_salida_id bigint,
  cantidad numeric not null default 1,
  proveedor_at_id bigint,
  constraint ruta_paso_pkey PRIMARY KEY (id),
  constraint ruta_paso_ruta_orden_key UNIQUE (ruta_id, orden) DEFERRABLE INITIALLY DEFERRED,
  constraint ruta_paso_comp_entrada_id_fkey FOREIGN KEY (comp_entrada_id) REFERENCES "GP2".componente(id),
  constraint ruta_paso_comp_salida_id_fkey FOREIGN KEY (comp_salida_id) REFERENCES "GP2".componente(id),
  constraint ruta_paso_matriz_id_fkey FOREIGN KEY (matriz_id) REFERENCES "GP2".matriz(id),
  constraint ruta_paso_proveedor_at_id_fkey FOREIGN KEY (proveedor_at_id) REFERENCES "GP2".proveedor_at(id),
  constraint ruta_paso_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES "GP2".proveedor_servicio(id),
  constraint ruta_paso_ruta_id_fkey FOREIGN KEY (ruta_id) REFERENCES "GP2".ruta(id),
  constraint ruta_paso_tallerista_id_fkey FOREIGN KEY (tallerista_id) REFERENCES "GP2".tallerista(id),
  constraint ruta_paso_tipo_paso_chk CHECK ((tipo_paso = ANY (ARRAY['ingreso'::text, 'insumo'::text, 'matriz'::text, 'proveedor_servicio'::text, 'tallerista'::text, 'virgilio'::text, 'proveedor_at'::text])))
);
comment on table "GP2".ruta_paso is 'Pasos de la ruta en orden: tipo (matriz / proveedor_servicio / tallerista), quien, componente que entra y componente que sale, cantidad. Fuente de v_contraparte_parte.';
comment on column "GP2".ruta_paso.proveedor_at_id is 'Prov. Art. Terminado del paso, cuando tipo_paso = ''proveedor_at''. El articulo llega terminado de el; lo que se le manda es el carton y la caja.';

comment on column "GP2".ruta_paso.cantidad is 'NO LA LEE NADIE: ni una funcion, ni una vista, ni un bundle la exponen. Duplica articulo_componente.cantidad y los dos ya divergieron una vez (58 pasos, alineados el 2026-09-11; el invariante AA de db/verificar.sql lo impide desde entonces). Candidata a borrarse, pero antes hay que decidir que significa en los pasos que NO son de insumo (matriz, proveedor_servicio, tallerista), donde hoy tampoco la lee nadie. Idea 7321.';
-- ---------- ruta_revision ----------
create table "GP2".ruta_revision (
  id bigint generated by default as identity not null,
  firma text not null,
  articulo text not null default ''::text,
  fleje text not null default ''::text,
  estado text not null,
  problema text,
  usuario text not null default ''::text,
  en timestamp with time zone not null default now(),
  resuelto_en timestamp with time zone,
  constraint ruta_revision_pkey PRIMARY KEY (id),
  constraint ruta_revision_firma_key UNIQUE (firma),
  constraint ruta_revision_estado_check CHECK ((estado = ANY (ARRAY['confirmada'::text, 'pendiente'::text, 'resuelto'::text])))
);
comment on table "GP2".ruta_revision is 'Revision de rutas desde Despiece x Articulo (ex ruta_confirmada + ruta_problema, 2026-09-04). Una fila por firma: confirmada / pendiente (problema) / resuelto.';

-- ---------- sector ----------
create table "GP2".sector (
  id bigint generated by default as identity not null,
  tipo text not null,
  nombre text not null,
  oc_rubro_id bigint,
  oc_pide boolean not null default true,
  es_insumo boolean not null default false,
  constraint sector_pkey PRIMARY KEY (id),
  constraint sector_nombre_key UNIQUE (nombre),
  constraint sector_oc_rubro_id_fkey FOREIGN KEY (oc_rubro_id) REFERENCES "GP2".sector(id),
  constraint sector_tipo_chk CHECK ((tipo = ANY (ARRAY['crudo'::text, 'procesado'::text, 'movimiento'::text, 'afilado'::text, 'fleje'::text, 'plástico'::text, 'bombilla'::text, 'remache'::text, 'garage'::text, 'cartón'::text, 'caja'::text, 'terminado'::text, 'materia_prima'::text])))
);
comment on table "GP2".sector is 'Sectores de la fabrica (tipo, es_insumo, rubro y si pide OC). Cada sector es una ubicacion de stock.';
comment on column "GP2".sector.oc_rubro_id is 'Rubro al que sube este sector en la pantalla de OC. NULL = es su propio rubro.';
comment on column "GP2".sector.oc_pide is 'false = este sector NO se compra por OC (no aparece en Generar OC).';
comment on column "GP2".sector.es_insumo is 'true = sector de insumos comprados (entra por Recepcion, sale en la OC, sin ruta que lo produzca). Antes: lista fija de ids en _es_sector_insumo.';

-- ---------- tallerista ----------
create table "GP2".tallerista (
  id bigint generated by default as identity not null,
  cod_prov text,
  nombre text not null,
  ubicacion_stock_id bigint,
  activo boolean not null default true,
  constraint tallerista_pkey PRIMARY KEY (id),
  constraint tallerista_nombre_key UNIQUE (nombre),
  constraint tallerista_ubicacion_stock_id_fkey FOREIGN KEY (ubicacion_stock_id) REFERENCES "GP2".ubicacion(id)
);
comment on table "GP2".tallerista is 'Talleristas (activo, ubicacion_stock_id cuando comparten deposito, p.ej. Carlos Aguirre en Pedernera). Cada uno tiene su ubicacion.';
comment on column "GP2".tallerista.ubicacion_stock_id is 'Ubicación de stock efectiva. Cuando el tallerista comparte depósito con otro actor (típicamente un proveedor_servicio), apunta a la ubi de ese depósito compartido. Si es NULL, se usa la ubi nativa (tipo=tallerista, ref_id=this.id).';
comment on column "GP2".tallerista.activo is 'false = no aparece en las pantallas de Envio/Entrega de talleristas. Se usa para sacar de circulacion sin borrar la fila, que arrastra ubicacion e historial de movimientos. Maspoli (id 7) quedo inactivo el 2026-09-03 al pasar a proveedor de servicio.';

-- ---------- tarifa_servicio ----------
create table "GP2".tarifa_servicio (
  id bigint generated always as identity not null,
  proveedor_servicio_id bigint not null,
  proceso text not null,
  precio_kg numeric,
  precio_uni numeric,
  moneda text not null default 'ARS'::text,
  origen text,
  actualizado_en timestamp with time zone not null default now(),
  constraint tarifa_servicio_pkey PRIMARY KEY (id),
  constraint tarifa_servicio_proveedor_servicio_id_proceso_key UNIQUE (proveedor_servicio_id, proceso),
  constraint tarifa_servicio_proceso_fkey FOREIGN KEY (proceso) REFERENCES "GP2".proceso(nombre) ON UPDATE CASCADE,
  constraint tarifa_servicio_proveedor_servicio_id_fkey FOREIGN KEY (proveedor_servicio_id) REFERENCES "GP2".proveedor_servicio(id),
  constraint tarifa_servicio_moneda_chk CHECK ((moneda = ANY (ARRAY['ARS'::text, 'USD'::text]))),
  constraint tarifa_servicio_precio_chk CHECK (((precio_kg IS NOT NULL) OR (precio_uni IS NOT NULL)))
);
comment on table "GP2".tarifa_servicio is 'Precio del servicio de un PS POR PROCESO (6 filas). OJO: hoy solo funciona como RELLENO -- v_costo_componente la engancha por pz.proceso, que sale de precio_servicio_pieza, asi que sin fila por pieza la tarifa NUNCA aplica. No la nombra ninguna funcion, solo esa vista. Idea 7332.';
-- ---------- tipo_cambio ----------
create table "GP2".tipo_cambio (
  fecha date not null,
  compra numeric,
  venta numeric not null,
  fuente text not null default 'dolarapi.com/oficial'::text,
  obtenido_en timestamp with time zone not null default now(),
  constraint tipo_cambio_pkey PRIMARY KEY (fecha)
);
comment on table "GP2".tipo_cambio is 'Dolar oficial diario (compra/venta/fuente); lo carga el cron gp2-dolar-oficial via actualizar_dolar_oficial.';

-- ---------- tipo_movimiento ----------
create table "GP2".tipo_movimiento (
  clave text not null,
  label text not null,
  lado text not null,
  clase text,
  orden integer not null default 100,
  constraint tipo_movimiento_pkey PRIMARY KEY (clave),
  constraint tipo_movimiento_lado_check CHECK ((lado = ANY (ARRAY['ent'::text, 'sal'::text, 'neto'::text])))
);
comment on table "GP2".tipo_movimiento is 'Vocabulario de movimiento.tipo_mov con su etiqueta para pantalla. Unica fuente: el CHECK viejo y los mapas TIPOS del JS salen de aca (2026-09-11).';

-- ---------- ubicacion ----------
create table "GP2".ubicacion (
  id bigint generated by default as identity not null,
  tipo text not null,
  ref_id bigint,
  nombre text,
  meses_minimo numeric,
  meses_stock numeric,
  constraint ubicacion_pkey PRIMARY KEY (id),
  constraint ubicacion_tipo_chk CHECK ((tipo = ANY (ARRAY['sector'::text, 'tallerista'::text, 'proveedor_servicio'::text, 'proveedor_at'::text, 'virgilio'::text, 'analisis'::text, 'inyector'::text, 'virgilio_sector'::text])))
);
comment on table "GP2".ubicacion is 'Ubicaciones de stock: una por sector, PS, tallerista, Prov AT e INYECTOR (tipo inyector, ref_id = proveedor_insumo.id: materia prima plastica en poder del inyector, 2026-09-10), mas Virgilio y "Para Analizar" (singletons). Se resuelven con ubic_de(tipo, ref_id); indice unico (tipo, ref_id).';
comment on column "GP2".ubicacion.ref_id is 'Referencia al id del sector/proveedor/tallerista según tipo. Es NULL sólo para tipos generales sin fila propia: virgilio, analisis.';

-- ---------- uni_x_articulo_x_caja ----------
create table "GP2".uni_x_articulo_x_caja (
  id bigint not null default nextval('"GP2".uni_x_articulo_x_caja_id_seq'::regclass),
  empresa text,
  cod_art text not null,
  descripcion text,
  uni_x_caja integer not null,
  n_caja text,
  creado_en timestamp with time zone not null default now(),
  constraint uni_x_articulo_x_caja_pkey PRIMARY KEY (id),
  constraint uni_x_articulo_x_caja_empresa_chk CHECK ((empresa = ANY (ARRAY['CH'::text, 'LK'::text])))
);
comment on table "GP2".uni_x_articulo_x_caja is 'Unidades de cada articulo que entran por caja, por empresa (CH / LK). Lo lee Control AT.';
comment on column "GP2".uni_x_articulo_x_caja.descripcion is 'Como llama al articulo el catalogo del que salio la fila (LK o CH). Difiere de articulo.descripcion en 149 filas, y 243 de las 434 filas son CH, del catalogo del vecino, que ni siquiera tienen articulo en GP2. No pisarla con articulo.descripcion.';
comment on column "GP2".uni_x_articulo_x_caja.n_caja is 'Numero de caja como TEXTO, mientras articulo_prov_at.n_caja es integer. Hay 4 filas con ''P'', asi que el tipo no se puede unificar sin decidir que significa esa P (o si son 4 filas para corregir). Ojo ademas: el codigo de caja NO es el numero -- el codigo A8 es la Caja N2, los codigos son posicion de estanteria.';
-- ---------- virgilio_espejo_pend ----------
create table "GP2".virgilio_espejo_pend (
  id bigint generated always as identity not null,
  entrega_id bigint,
  fecha text,
  nombre_tall text,
  cod text,
  cajas numeric,
  motivo text,
  creado_en timestamp with time zone not null default now(),
  resuelto_en timestamp with time zone,
  resultado jsonb,
  constraint virgilio_espejo_pend_pkey PRIMARY KEY (id)
);
comment on table "GP2".virgilio_espejo_pend is 'Entregas de Virgilio (public."Entregas Tallerista Virgilio") que el espejo no pudo cruzar a GP2 (falta alias o codigo), con el motivo.';
comment on column "GP2".virgilio_espejo_pend.resuelto_en is 'Cuando se reproceso con exito (reprocesar_espejo_virgilio). Null = sigue pendiente.';
comment on column "GP2".virgilio_espejo_pend.resultado is 'Lo que devolvio recepcion_virgilio al reprocesar, o el motivo por el que sigue sin poder.';

-- ============ INDICES (no asociados a constraints) ============

CREATE INDEX __sim_base_idx ON "GP2".__sim_base USING btree (comp, ubic);
CREATE UNIQUE INDEX articulo_componente_uq ON "GP2".articulo_componente USING btree (articulo_id, componente_id);
CREATE UNIQUE INDEX articulo_prov_at_prov_cod_uq ON "GP2".articulo_prov_at USING btree (proveedor_at_id, cod_art);
CREATE UNIQUE INDEX componente_bom_uq ON "GP2".componente_bom USING btree (componente_padre_id, componente_hijo_id);
CREATE UNIQUE INDEX componente_codigo_virgilio_uk ON "GP2".componente USING btree (codigo_virgilio) WHERE (codigo_virgilio IS NOT NULL);
CREATE UNIQUE INDEX componente_sector_codigo_uq ON "GP2".componente USING btree (sector_id, codigo) WHERE ((codigo IS NOT NULL) AND (codigo <> ''::text));
CREATE INDEX idx_articulo_componente_articulo_id ON "GP2".articulo_componente USING btree (articulo_id);
CREATE INDEX idx_articulo_componente_componente_id ON "GP2".articulo_componente USING btree (componente_id);
CREATE INDEX idx_carton_categoria_formato ON "GP2".carton_categoria USING btree (formato);
CREATE INDEX idx_componente_bom_componente_hijo_id ON "GP2".componente_bom USING btree (componente_hijo_id);
CREATE INDEX idx_componente_bom_componente_padre_id ON "GP2".componente_bom USING btree (componente_padre_id);
CREATE INDEX idx_componente_carton_categoria ON "GP2".componente USING btree (carton_categoria);
CREATE INDEX idx_componente_carton_formato ON "GP2".componente USING btree (carton_formato);
CREATE INDEX idx_componente_sector_id ON "GP2".componente USING btree (sector_id);
CREATE INDEX idx_entrega_prov_at_prov ON "GP2".entrega_prov_at USING btree (proveedor_at_id);
CREATE INDEX idx_faltante_marcado_abierto ON "GP2".faltante_marcado USING btree (componente_id, origen) WHERE (resuelto_en IS NULL);
CREATE INDEX idx_inventario_ubicacion_id ON "GP2".inventario USING btree (ubicacion_id);
CREATE INDEX idx_movimiento_comp_id ON "GP2".movimiento USING btree (comp_id);
CREATE INDEX idx_movimiento_comp_transformado_id ON "GP2".movimiento USING btree (comp_transformado_id);
CREATE INDEX idx_movimiento_ubic_destino_id ON "GP2".movimiento USING btree (ubic_destino_id);
CREATE INDEX idx_movimiento_ubic_origen_id ON "GP2".movimiento USING btree (ubic_origen_id);
CREATE INDEX idx_orden_compra_item_componente_id ON "GP2".orden_compra_item USING btree (componente_id);
CREATE INDEX idx_orden_compra_item_oc_id ON "GP2".orden_compra_item USING btree (oc_id);
CREATE INDEX idx_precio_proveedor_componente_id ON "GP2".precio_proveedor USING btree (componente_id);
CREATE INDEX idx_produccion_matriz_id ON "GP2".produccion USING btree (matriz_id);
CREATE INDEX idx_recepcion_insumo_componente_id ON "GP2".recepcion_insumo USING btree (componente_id);
CREATE INDEX idx_rollo_evento_control_rollo_id ON "GP2".rollo_evento USING btree (control_rollo_id);
CREATE INDEX idx_rollo_uso_componente_id ON "GP2".rollo_uso USING btree (componente_id);
CREATE INDEX idx_rollo_uso_rollo_evento_id ON "GP2".rollo_uso USING btree (rollo_evento_id);
CREATE INDEX idx_ruta_articulo_id ON "GP2".ruta USING btree (articulo_id);
CREATE INDEX idx_ruta_paso_comp_entrada_id ON "GP2".ruta_paso USING btree (comp_entrada_id);
CREATE INDEX idx_ruta_paso_comp_salida_id ON "GP2".ruta_paso USING btree (comp_salida_id);
CREATE INDEX idx_ruta_paso_matriz_id ON "GP2".ruta_paso USING btree (matriz_id);
CREATE INDEX idx_ruta_paso_proveedor_id ON "GP2".ruta_paso USING btree (proveedor_id);
CREATE INDEX idx_ruta_paso_ruta_id ON "GP2".ruta_paso USING btree (ruta_id);
CREATE INDEX idx_ruta_paso_tallerista_id ON "GP2".ruta_paso USING btree (tallerista_id);
CREATE INDEX idx_uxc_cod_art ON "GP2".uni_x_articulo_x_caja USING btree (cod_art);
CREATE UNIQUE INDEX inventario_comp_ubic_uk ON "GP2".inventario USING btree (componente_id, ubicacion_id);
CREATE INDEX ix_crono_fecha ON "GP2".relevamiento_cronograma USING btree (fecha);
CREATE UNIQUE INDEX relevamiento_cronograma_sector_fecha_uq ON "GP2".relevamiento_cronograma USING btree (sector_id, fecha) WHERE (sector_id IS NOT NULL);
CREATE INDEX ix_planilla_fila_datos ON "GP2".planilla_fila USING gin (datos);
CREATE INDEX ix_planilla_fila_hoja ON "GP2".planilla_fila USING btree (snapshot_id, hoja);
CREATE INDEX ix_pps_proveedor ON "GP2".parte_proveedor_servicio USING btree (proveedor_servicio_id);
CREATE INDEX ix_relev_item_relev ON "GP2".relevamiento_item USING btree (relevamiento_id);
CREATE INDEX ix_relev_sector_fecha ON "GP2".relevamiento USING btree (sector_id, fecha DESC);
CREATE INDEX movimiento_fecha_idx ON "GP2".movimiento USING btree (fecha DESC, id DESC);
CREATE INDEX movimiento_tipo_comp_idx ON "GP2".movimiento USING btree (tipo_mov, comp_id);
CREATE UNIQUE INDEX orden_compra_item_oc_comp_uq ON "GP2".orden_compra_item USING btree (oc_id, componente_id);
CREATE UNIQUE INDEX planilla_snapshot_vigente_uq ON "GP2".planilla_snapshot USING btree (vigente) WHERE vigente;
CREATE INDEX produccion_legajo_fecha_idx ON "GP2".produccion USING btree (legajo, fecha);
CREATE UNIQUE INDEX proveedor_insumo_cod_prov_uq ON "GP2".proveedor_insumo USING btree (cod_prov) WHERE (cod_prov IS NOT NULL);
CREATE UNIQUE INDEX proveedor_servicio_nombre_uq ON "GP2".proveedor_servicio USING btree (lower(btrim(nombre)));
CREATE INDEX recepcion_control_rollo_control_idx ON "GP2".recepcion_control_rollo USING btree (control_id);
CREATE INDEX rollo_evento_comp_idx ON "GP2".rollo_evento USING btree (componente_id, kg_por_rollo, fecha);
CREATE INDEX rollo_uso_abierto_idx ON "GP2".rollo_uso USING btree (legajo) WHERE (ts_fin IS NULL);
CREATE INDEX ruta_revision_estado_idx ON "GP2".ruta_revision USING btree (estado);
CREATE UNIQUE INDEX ubicacion_singleton_uq ON "GP2".ubicacion USING btree (tipo) WHERE (tipo = ANY (ARRAY['virgilio'::text, 'analisis'::text]));
CREATE UNIQUE INDEX ubicacion_tipo_ref_uq ON "GP2".ubicacion USING btree (tipo, ref_id) WHERE (ref_id IS NOT NULL);
CREATE UNIQUE INDEX uq_componente_codigo_sector ON "GP2".componente USING btree (upper(btrim(codigo)), sector_id) WHERE (codigo IS NOT NULL);
CREATE UNIQUE INDEX uq_pps_un_asignado ON "GP2".parte_proveedor_servicio USING btree (componente_id) WHERE asignado;
CREATE UNIQUE INDEX uq_produccion_id_ejecucion ON "GP2".produccion USING btree (id_ejecucion) WHERE (id_ejecucion IS NOT NULL);

-- ============ TRIGGERS ============

CREATE TRIGGER trg_maximos_receta AFTER INSERT OR DELETE OR UPDATE ON "GP2".articulo_componente FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_recalc_maximos_insumos();

CREATE TRIGGER trg_maximos_cajones_componente AFTER UPDATE OF uni_x_cajon ON "GP2".componente FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_recalc_maximos_cajones();

CREATE TRIGGER trg_maximos_est_madre AFTER INSERT OR DELETE OR UPDATE ON "GP2".est_madre FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_recalc_maximos_insumos();

CREATE TRIGGER trg_movimiento_aplicar AFTER INSERT OR DELETE OR UPDATE ON "GP2".movimiento FOR EACH ROW EXECUTE FUNCTION "GP2".fn_movimiento_aplicar();

CREATE TRIGGER trg_movimiento_calc BEFORE INSERT OR UPDATE ON "GP2".movimiento FOR EACH ROW EXECUTE FUNCTION "GP2".fn_movimiento_calc();

CREATE TRIGGER trg_maximos_cajones_parametro AFTER UPDATE OF valor ON "GP2".parametro FOR EACH ROW WHEN ((new.clave = 'max_cajones_x_ubicacion'::text)) EXECUTE FUNCTION "GP2".fn_recalc_maximos_cajones();

CREATE TRIGGER trg_material_mejor_proveedor AFTER INSERT OR DELETE OR UPDATE ON "GP2".precio_proveedor FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_material_mejor_proveedor();

CREATE TRIGGER trg_precio_tallerista_kg BEFORE INSERT OR UPDATE ON "GP2".precio_tallerista FOR EACH ROW EXECUTE FUNCTION "GP2".fn_precio_tallerista_kg();

CREATE TRIGGER trg_ubicacion_proveedor_at AFTER INSERT ON "GP2".proveedor_at FOR EACH ROW EXECUTE FUNCTION "GP2".fn_ubicacion_de_contraparte();

CREATE TRIGGER trg_ubicacion_proveedor_servicio AFTER INSERT ON "GP2".proveedor_servicio FOR EACH ROW EXECUTE FUNCTION "GP2".fn_ubicacion_de_contraparte();

CREATE TRIGGER trg_rollo_desde_control AFTER INSERT OR DELETE OR UPDATE ON "GP2".recepcion_control_rollo FOR EACH ROW EXECUTE FUNCTION "GP2".fn_rollo_desde_control();

CREATE TRIGGER trg_maximos_rutas AFTER INSERT OR DELETE OR UPDATE ON "GP2".ruta_paso FOR EACH STATEMENT EXECUTE FUNCTION "GP2".fn_recalc_maximos_insumos();

CREATE TRIGGER trg_ubicacion_sector AFTER INSERT OR UPDATE OF es_insumo ON "GP2".sector FOR EACH ROW EXECUTE FUNCTION "GP2".fn_ubicacion_de_contraparte();

CREATE TRIGGER trg_ubicacion_tallerista AFTER INSERT ON "GP2".tallerista FOR EACH ROW EXECUTE FUNCTION "GP2".fn_ubicacion_de_contraparte();

-- ============ ROW LEVEL SECURITY ============

alter table "GP2".__sim_base enable row level security;
alter table "GP2".articulo enable row level security;
alter table "GP2".articulo_componente enable row level security;
alter table "GP2".articulo_prov_at enable row level security;
alter table "GP2".carton_categoria enable row level security;
alter table "GP2".carton_formato enable row level security;
alter table "GP2".componente enable row level security;
alter table "GP2".componente_bom enable row level security;
alter table "GP2".contraparte_alias enable row level security;
alter table "GP2".empleado enable row level security;
alter table "GP2".entrega_prov_at enable row level security;
alter table "GP2".est_madre enable row level security;
alter table "GP2".faltante_marcado enable row level security;
alter table "GP2".familia enable row level security;
alter table "GP2".fleje_detalle enable row level security;
alter table "GP2".inventario enable row level security;
alter table "GP2".matriz enable row level security;
alter table "GP2".movimiento enable row level security;
alter table "GP2".orden_compra enable row level security;
alter table "GP2".orden_compra_item enable row level security;
alter table "GP2".parametro enable row level security;
alter table "GP2".parte_proveedor_servicio enable row level security;
alter table "GP2".planilla_fila enable row level security;
alter table "GP2".planilla_snapshot enable row level security;
alter table "GP2".precio_proveedor enable row level security;
alter table "GP2".precio_servicio_pieza enable row level security;
alter table "GP2".precio_tallerista enable row level security;
alter table "GP2".proceso enable row level security;
alter table "GP2".produccion enable row level security;
alter table "GP2".proveedor_at enable row level security;
alter table "GP2".proveedor_insumo enable row level security;
alter table "GP2".proveedor_servicio enable row level security;
alter table "GP2".recepcion_control enable row level security;
alter table "GP2".recepcion_control_rollo enable row level security;
alter table "GP2".recepcion_insumo enable row level security;
alter table "GP2".relevamiento enable row level security;
alter table "GP2".relevamiento_cronograma enable row level security;
alter table "GP2".relevamiento_item enable row level security;
alter table "GP2".rollo_evento enable row level security;
alter table "GP2".rollo_uso enable row level security;
alter table "GP2".ruta enable row level security;
alter table "GP2".ruta_paso enable row level security;
alter table "GP2".ruta_revision enable row level security;
alter table "GP2".sector enable row level security;
alter table "GP2".tallerista enable row level security;
alter table "GP2".tarifa_servicio enable row level security;
alter table "GP2".tipo_cambio enable row level security;
alter table "GP2".tipo_movimiento enable row level security;
alter table "GP2".ubicacion enable row level security;
alter table "GP2".uni_x_articulo_x_caja enable row level security;
alter table "GP2".virgilio_espejo_pend enable row level security;

-- ============ POLICIES ============
-- Todas son de SELECT: ninguna tabla GP2 acepta escritura anonima directa (la escritura va por RPC SECURITY DEFINER).

create policy __sim_base_sel on "GP2".__sim_base for select to public using (false);
create policy p_gp2_select on "GP2".articulo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".articulo_componente for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".articulo_prov_at for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".carton_categoria for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".carton_formato for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".componente for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".componente_bom for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".contraparte_alias for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".empleado for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".entrega_prov_at for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".est_madre for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".faltante_marcado for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".familia for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".fleje_detalle for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".inventario for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".matriz for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".movimiento for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".orden_compra for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".orden_compra_item for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".parametro for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".parte_proveedor_servicio for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".planilla_fila for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".planilla_snapshot for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".precio_proveedor for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".precio_servicio_pieza for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".precio_tallerista for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proceso for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".produccion for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proveedor_at for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proveedor_insumo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".proveedor_servicio for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".recepcion_control for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".recepcion_control_rollo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".recepcion_insumo for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".relevamiento for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".relevamiento_cronograma for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".relevamiento_item for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".rollo_evento for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".rollo_uso for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".ruta for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".ruta_paso for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".ruta_revision for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".sector for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".tallerista for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".tarifa_servicio for select to anon, authenticated using (true);
create policy sel_anon on "GP2".tipo_cambio for select to anon, authenticated using (true);
create policy tipo_movimiento_sel on "GP2".tipo_movimiento for select to public using (true);
create policy p_gp2_select on "GP2".ubicacion for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".uni_x_articulo_x_caja for select to anon, authenticated using (true);
create policy p_gp2_select on "GP2".virgilio_espejo_pend for select to anon, authenticated using (true);
