-- Backup PPP_Web_Config · 2026-09-05 ~02:00 ART · antes de agregar espejo_np_corte_lk / _chef
-- Restore: ejecutar tal cual (on conflict do nothing: no pisa lo que ya esté).
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('tanda_m3_min',0.60,NULL,'m³ deseable mínimo de una tanda. NO bloquea: en el histórico 33 de 56 tandas salieron por debajo. Sirve para avisar, no para retener.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('dias_hasta_entrega',0,NULL,'Días desde que se arma la tanda hasta la fecha de entrega. 0 = el mismo día. ⚠ Sin evidencia histórica: la fecha_entrega de la PPP de ISIS la carga una persona (mediana 11 días desde el último pedido, mínimo 2, máximo 96). Este es el parámetro a mover si el criterio es otro.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('saltar_fin_de_semana',1,NULL,'1 = si la fecha de entrega cae sábado o domingo, se corre al lunes. En 120 días de histórico no hay ni una sola entrega de fin de semana.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('ventana_dias',30,NULL,'Dias hacia atras que el armado automatico le pide a LK/Chef. Espejo de PWEB_VENTANA_DIAS del front.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('tanda_m3_max_mezcla',0.80,NULL,'Tope de m3 para JUNTAR clientes distintos (dueno, 2026-09-04). No parte a un cliente: si uno solo pide mas, se va solo con todo lo suyo.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('m3_max_dia',5.00,NULL,'Cuantos m3 se arman por dia en total (las dos empresas juntas). El dueno dijo 4 a 5; se toma 5. Lo que no entra espera al dia siguiente: esa cola es la demora.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('tanda_prefijo',null,'GV-','Prefijo de los codigos de tanda de Gestion MIENTRAS CONVIVE con Produccion: son tandas de prueba y no se pueden confundir con las de ISIS. ⚠ CUANDO GESTION TOME CONTROL Y SEA LA VERSION QUE USAMOS, VACIAR ESTE CAMPO ('''') PARA SEGUIR CON LA NUMERACION QUE DEJO VIRGILIO (LETRA+NN+LETRA, D19J).') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('zonas_automaticas',null,'1,2','Numeros de zona que el armado automatico programa SOLO. El resto (zonas 3+, Retira, Super, Expo, y cualquier cosa sin zona) queda SIN tanda, esperando que una persona la programe a mano. Vacio = ninguna zona automatica. Regla del dueno, 2026-09-04.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('numeracion_activa',1,NULL,'0 = Gestion NO asigna numeros de NP. Hoy la NP la manda ISIS a la hoja de calculos y la usa Produccion. Se prende (=1) el dia que Gestion tome control: ahi numera los pedidos pendientes y los que vayan cayendo.') on conflict (clave) do nothing;
insert into public."PPP_Web_Config"(clave,valor,valor_texto,descripcion) values ('gestion_desde',null,'2026-09-03',NULL) on conflict (clave) do nothing;
