-- Backup 2026-09-07 ANTES de la renumeración v13.70 (NP web = contador propio, un número por bloque; dueño: 'el pedido tiene
-- que ser único, no 1350-1/1350-2/1350-3; LK y 4 dígitos'). Restore: ejecutar entero (vuelve np = order_id y las etiquetas con sufijo).
-- Además volver a aplicar sql/gv_np_es_pedido.sql (label con sufijo + asignar np = order_id) y borrar el índice único:
--   drop index if exists public.ppp_web_np_empresa_np_uk;

update public."PPP_Web_NP" set np = 216 where empresa = 'chef' and order_id = 216 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 216 where empresa = 'chef' and order_id = 216 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'CH 0216' where empresa = 'chef' and order_id = 216 and np_idx = 1;
update public."PPP_Web_NP" set np = 216 where empresa = 'chef' and order_id = 216 and np_idx = 2;
update public."PPP_Web_Programacion" set np = 216 where empresa = 'chef' and order_id = 216 and np_idx = 2;
update public."PPP_Web_Base" set np_label = 'CH 0216-2' where empresa = 'chef' and order_id = 216 and np_idx = 2;
update public."PPP_Web_NP" set np = 217 where empresa = 'chef' and order_id = 217 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 217 where empresa = 'chef' and order_id = 217 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'CH 0217' where empresa = 'chef' and order_id = 217 and np_idx = 1;
update public."PPP_Web_NP" set np = 1340 where empresa = 'lk' and order_id = 1340 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1340 where empresa = 'lk' and order_id = 1340 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1340' where empresa = 'lk' and order_id = 1340 and np_idx = 1;
update public."PPP_Web_NP" set np = 1341 where empresa = 'lk' and order_id = 1341 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1341 where empresa = 'lk' and order_id = 1341 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1341' where empresa = 'lk' and order_id = 1341 and np_idx = 1;
update public."PPP_Web_NP" set np = 1342 where empresa = 'lk' and order_id = 1342 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1342 where empresa = 'lk' and order_id = 1342 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1342' where empresa = 'lk' and order_id = 1342 and np_idx = 1;
update public."PPP_Web_NP" set np = 1343 where empresa = 'lk' and order_id = 1343 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1343 where empresa = 'lk' and order_id = 1343 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1343' where empresa = 'lk' and order_id = 1343 and np_idx = 1;
update public."PPP_Web_NP" set np = 1343 where empresa = 'lk' and order_id = 1343 and np_idx = 2;
update public."PPP_Web_Programacion" set np = 1343 where empresa = 'lk' and order_id = 1343 and np_idx = 2;
update public."PPP_Web_Base" set np_label = 'LK 1343-2' where empresa = 'lk' and order_id = 1343 and np_idx = 2;
update public."PPP_Web_NP" set np = 1343 where empresa = 'lk' and order_id = 1343 and np_idx = 3;
update public."PPP_Web_Programacion" set np = 1343 where empresa = 'lk' and order_id = 1343 and np_idx = 3;
update public."PPP_Web_Base" set np_label = 'LK 1343-3' where empresa = 'lk' and order_id = 1343 and np_idx = 3;
update public."PPP_Web_NP" set np = 1344 where empresa = 'lk' and order_id = 1344 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1344 where empresa = 'lk' and order_id = 1344 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1344' where empresa = 'lk' and order_id = 1344 and np_idx = 1;
update public."PPP_Web_NP" set np = 1344 where empresa = 'lk' and order_id = 1344 and np_idx = 2;
update public."PPP_Web_Programacion" set np = 1344 where empresa = 'lk' and order_id = 1344 and np_idx = 2;
update public."PPP_Web_Base" set np_label = 'LK 1344-2' where empresa = 'lk' and order_id = 1344 and np_idx = 2;
update public."PPP_Web_NP" set np = 1345 where empresa = 'lk' and order_id = 1345 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1345 where empresa = 'lk' and order_id = 1345 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1345' where empresa = 'lk' and order_id = 1345 and np_idx = 1;
update public."PPP_Web_NP" set np = 1345 where empresa = 'lk' and order_id = 1345 and np_idx = 2;
update public."PPP_Web_Programacion" set np = 1345 where empresa = 'lk' and order_id = 1345 and np_idx = 2;
update public."PPP_Web_Base" set np_label = 'LK 1345-2' where empresa = 'lk' and order_id = 1345 and np_idx = 2;
update public."PPP_Web_NP" set np = 1346 where empresa = 'lk' and order_id = 1346 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1346 where empresa = 'lk' and order_id = 1346 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1346' where empresa = 'lk' and order_id = 1346 and np_idx = 1;
update public."PPP_Web_NP" set np = 1347 where empresa = 'lk' and order_id = 1347 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1347 where empresa = 'lk' and order_id = 1347 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1347' where empresa = 'lk' and order_id = 1347 and np_idx = 1;
update public."PPP_Web_NP" set np = 1347 where empresa = 'lk' and order_id = 1347 and np_idx = 2;
update public."PPP_Web_Programacion" set np = 1347 where empresa = 'lk' and order_id = 1347 and np_idx = 2;
update public."PPP_Web_Base" set np_label = 'LK 1347-2' where empresa = 'lk' and order_id = 1347 and np_idx = 2;
update public."PPP_Web_NP" set np = 1347 where empresa = 'lk' and order_id = 1347 and np_idx = 3;
update public."PPP_Web_Programacion" set np = 1347 where empresa = 'lk' and order_id = 1347 and np_idx = 3;
update public."PPP_Web_Base" set np_label = 'LK 1347-3' where empresa = 'lk' and order_id = 1347 and np_idx = 3;
update public."PPP_Web_NP" set np = 1348 where empresa = 'lk' and order_id = 1348 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1348 where empresa = 'lk' and order_id = 1348 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1348' where empresa = 'lk' and order_id = 1348 and np_idx = 1;
update public."PPP_Web_NP" set np = 1348 where empresa = 'lk' and order_id = 1348 and np_idx = 2;
update public."PPP_Web_Programacion" set np = 1348 where empresa = 'lk' and order_id = 1348 and np_idx = 2;
update public."PPP_Web_Base" set np_label = 'LK 1348-2' where empresa = 'lk' and order_id = 1348 and np_idx = 2;
update public."PPP_Web_NP" set np = 1348 where empresa = 'lk' and order_id = 1348 and np_idx = 3;
update public."PPP_Web_Programacion" set np = 1348 where empresa = 'lk' and order_id = 1348 and np_idx = 3;
update public."PPP_Web_Base" set np_label = 'LK 1348-3' where empresa = 'lk' and order_id = 1348 and np_idx = 3;
update public."PPP_Web_NP" set np = 1349 where empresa = 'lk' and order_id = 1349 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1349 where empresa = 'lk' and order_id = 1349 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1349' where empresa = 'lk' and order_id = 1349 and np_idx = 1;
update public."PPP_Web_NP" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1350' where empresa = 'lk' and order_id = 1350 and np_idx = 1;
update public."PPP_Web_NP" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 2;
update public."PPP_Web_Programacion" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 2;
update public."PPP_Web_Base" set np_label = 'LK 1350-2' where empresa = 'lk' and order_id = 1350 and np_idx = 2;
update public."PPP_Web_NP" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 3;
update public."PPP_Web_Programacion" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 3;
update public."PPP_Web_Base" set np_label = 'LK 1350-3' where empresa = 'lk' and order_id = 1350 and np_idx = 3;
update public."PPP_Web_NP" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 4;
update public."PPP_Web_Programacion" set np = 1350 where empresa = 'lk' and order_id = 1350 and np_idx = 4;
update public."PPP_Web_Base" set np_label = 'LK 1350-4' where empresa = 'lk' and order_id = 1350 and np_idx = 4;
update public."PPP_Web_NP" set np = 1351 where empresa = 'lk' and order_id = 1351 and np_idx = 1;
update public."PPP_Web_Programacion" set np = 1351 where empresa = 'lk' and order_id = 1351 and np_idx = 1;
update public."PPP_Web_Base" set np_label = 'LK 1351' where empresa = 'lk' and order_id = 1351 and np_idx = 1;
