-- v25.15 (Luis, 30/09): lo que Gestión Virgilio le ACEPTA a GP2 (Cervantes), en una tabla que leen los dos.
-- Espejo de "GP2".ingreso_virgilio (v25.14), en el otro sentido. Aplicado en vivo el 30/09: 24 filas
-- (7 aceptadas con código real, 17 todavía con código TMP-).
-- Fuente: Movimientos_Stock deposito='insumos', tipo='recepcion_insumo', ref ~ 'Cervantes'.
-- "aceptado" = el código ya no es TMP- (lo identificó un supervisor con «✓ Aceptar» / insumo_identificar).

create table if not exists "GP2".aceptado_virgilio (
  id            bigint generated by default as identity primary key,
  mov_id        bigint not null unique,
  fecha         timestamptz not null,
  cod_virgilio  text,
  aceptado      boolean not null,
  descripcion   text,
  cantidad      numeric,
  unidad        text,
  ubicacion     text,
  legajo        text,
  origen        text not null default 'recepcion_insumo',
  componente_id bigint,          -- vínculo con GP2.componente: falta el mapeo, no se adivina
  actualizado_en timestamptz not null default now()
);
alter table "GP2".aceptado_virgilio enable row level security;
create policy p_gp2_select on "GP2".aceptado_virgilio for select to anon, authenticated using (true);
revoke insert, update, delete, truncate on "GP2".aceptado_virgilio from anon, authenticated;
grant select on "GP2".aceptado_virgilio to anon, authenticated;

-- public.gv_gp2_aceptado_sync(): upsert por mov_id (sólo escribe si cambió) + poda de lo que ya no está.
-- Definición vigente: select pg_get_functiondef('public.gv_gp2_aceptado_sync()'::regprocedure);
-- Cron: gv-gp2-aceptado-sync '3-59/10 * * * *'.
-- Rollback: select cron.unschedule('gv-gp2-aceptado-sync'); drop function public.gv_gp2_aceptado_sync();
--           drop table "GP2".aceptado_virgilio;

-- 323ES pasa a Mixto (Luis, D4): Importados id 167 y GV_Importados_Baches id 134, LK → Mixto.
-- Backup: zz_backups."GV_Backup_323ES_marca_20260930".
