-- v25.11 (Luis, 30/09): destino «Cervantes» al recibir importados + aviso en la portada de GP2.
-- Aplicado en vivo el 30/09 (marcador de idempotencia dentro de las funciones: v25.10-cerv, no cambiarlo).
--
-- 1) Tabla del lado de GP2 (GP2 la LEE; la escribe sólo gv_imp_recibir, SECURITY DEFINER).
create table if not exists "GP2".ingreso_virgilio (
  id            bigint generated by default as identity primary key,
  creado_en     timestamptz default now(),
  creado_por    text,
  origen        text default 'importacion',
  recepcion_id  bigint,
  bache_id      bigint,
  cod_importado text,
  cod_insumo    text,
  descripcion   text,
  cantidad      numeric,
  unidad        text,                       -- 'cajas' | 'unidades'
  proveedor     text,
  pedido_ref    text,
  nota          text,
  estado        text default 'pendiente',   -- pendiente | confirmado | anulado
  confirmado_en timestamptz,
  confirmado_por text,
  ubicacion_id  bigint,                     -- lo completa GP2 al ubicar (falta implementar)
  componente_id bigint                      -- idem: vínculo con GP2.componente (falta el mapeo)
);
alter table "GP2".ingreso_virgilio enable row level security;
create policy p_gp2_select on "GP2".ingreso_virgilio for select to anon, authenticated using (true);
revoke insert, update, delete, truncate on "GP2".ingreso_virgilio from anon, authenticated;
create index if not exists ingreso_virgilio_pend on "GP2".ingreso_virgilio (creado_en) where estado = 'pendiente';

-- 2) public.gv_imp_recibir — cambios sobre la definición viva (pg_get_functiondef):
--    · acepta destino 'cervantes' (sector 'CERVANTES'). Con unidad 'uni' suma unidades y resuelve
--      cod_insumo contra vista_insumos; si no, cajas enteras.
--    · al grabar, 'cervantes' NO escribe Movimientos_Stock: inserta una fila en GP2.ingreso_virgilio
--      (estado pendiente) con recepcion_id / bache_id / código / descripción / cantidad / unidad.
--    · GV_Imp_Recepcion_Destino.unidad = la de la línea ('Uni' o 'cajas').
--
-- 3) public.gv_imp_recepcion_anular:
--    · frena si GP2 ya confirmó ("Cervantes ya confirmó que le llegó").
--    · pasa a 'anulado' la fila pendiente de GP2.ingreso_virgilio.
--    · los dos loops de stock saltean destino = 'cervantes' (no hubo movimiento que revertir).
--
-- Definición vigente: select pg_get_functiondef('public.gv_imp_recibir(bigint,text,numeric,jsonb,text,boolean,boolean,text)'::regprocedure);
--                     select pg_get_functiondef('public.gv_imp_recepcion_anular(bigint,text)'::regprocedure);
-- Rollback: quitar 'cervantes' de la lista de destinos válidos y el bloque «if v_dest = 'cervantes'»
--           en las dos funciones (partiendo de la definición viva), y `drop table "GP2".ingreso_virgilio;`
--           sólo si no tiene filas confirmadas.
