-- v14.94 — Baches de pedidos de importación (Gestión Virgilio)
-- Proyecto Supabase: hrxfctzncixxqmpfhskv
--
-- Problema: el módulo "Pedidos Importación" tenía UNA sola fecha de reingreso por artículo
-- (Importados.reingreso_est) y UN solo "en curso" (Importados.pedido_curso). Con dos pedidos
-- del mismo artículo con fechas distintas, la segunda fecha pisaba a la primera.
--
-- Solución: tabla de BACHES (fuente de verdad). Cada pedido en curso = un bache con su propia
-- fecha. Importados.pedido_curso y reingreso_est quedan como MIRROR derivado:
--   pedido_curso (por fila)                 = suma pendiente de baches en curso de esa fila
--   reingreso_est (por cod gv_cod_stock)    = fecha pendiente MÁS CERCANA (o NULL)
-- Así el front (En curso) y el feed a LK (lk_reingresos_feed → max(reingreso_est)) siguen
-- funcionando sin cambios: el mirror es uniforme por cod, la fecha más cercana llega a la página.
--
-- Backup previo: public."GV_Importados_curso_bkp_20260911" (id, cod_art, marca, pedido_curso, reingreso_est).

create table if not exists public."GV_Importados_Baches" (
  id                bigint generated by default as identity primary key,
  importado_id      bigint not null references public."Importados"(id) on delete cascade,
  cod_art           text not null,
  proveedor         text,
  marca             text,
  unidades          integer not null check (unidades > 0),
  unidades_llegadas integer not null default 0 check (unidades_llegadas >= 0),
  fecha_reingreso   date,
  estado            text not null default 'en_curso' check (estado in ('en_curso','llegado','anulado')),
  creado            timestamptz not null default now(),
  creado_por        text,
  actualizado       timestamptz not null default now()
);
create index if not exists gv_imp_baches_importado_idx on public."GV_Importados_Baches"(importado_id);
create index if not exists gv_imp_baches_cod_idx        on public."GV_Importados_Baches"(cod_art);
create index if not exists gv_imp_baches_estado_idx      on public."GV_Importados_Baches"(estado, fecha_reingreso);
alter table public."GV_Importados_Baches" enable row level security;
-- Sin policies para anon/authenticated: todo el acceso va por RPCs SECURITY DEFINER.

-- Backfill: el "en curso" existente pasa a ser un bache por fila (idempotente).
insert into public."GV_Importados_Baches"
  (importado_id, cod_art, proveedor, marca, unidades, unidades_llegadas, fecha_reingreso, estado, creado_por)
select im.id, im.cod_art, im.proveedor, im.marca,
       round(im.pedido_curso)::int, 0, im.reingreso_est, 'en_curso', 'backfill_20260911'
from public."Importados" im
where coalesce(im.pedido_curso,0) > 0
  and not exists (select 1 from public."GV_Importados_Baches" b where b.importado_id = im.id);

-- Recalcula los mirrors en Importados desde los baches.
create or replace function public.gv_importados_resync(p_importado_id bigint)
returns void language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_codstock text;
begin
  select gv_cod_stock(cod_art) into v_codstock from public."Importados" where id = p_importado_id;
  if v_codstock is null then return; end if;

  update public."Importados" im
  set pedido_curso = coalesce((
        select sum(greatest(0, b.unidades - b.unidades_llegadas))
        from public."GV_Importados_Baches" b
        where b.importado_id = im.id and b.estado = 'en_curso'), 0),
      actualizado = now()
  where im.id = p_importado_id;

  update public."Importados" im
  set reingreso_est = (
        select min(b.fecha_reingreso)
        from public."GV_Importados_Baches" b
        join public."Importados" im2 on im2.id = b.importado_id
        where gv_cod_stock(im2.cod_art) = v_codstock
          and b.estado = 'en_curso'
          and greatest(0, b.unidades - b.unidades_llegadas) > 0
          and b.fecha_reingreso is not null),
      actualizado = now()
  where gv_cod_stock(im.cod_art) = v_codstock;
end $$;

create or replace function public.gv_importado_bache_add(p_importado_id bigint, p_unidades numeric, p_fecha date default null, p_legajo text default null)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare r record; v_u int; v_id bigint;
begin
  if p_importado_id is null then raise exception 'importado_id requerido'; end if;
  v_u := round(coalesce(p_unidades,0));
  if v_u <= 0 then raise exception 'unidades debe ser > 0'; end if;
  select id, cod_art, proveedor, marca into r from public."Importados" where id = p_importado_id;
  if not found then raise exception 'Importado % no existe', p_importado_id; end if;
  insert into public."GV_Importados_Baches"(importado_id,cod_art,proveedor,marca,unidades,fecha_reingreso,estado,creado_por)
  values (r.id, r.cod_art, r.proveedor, r.marca, v_u, p_fecha, 'en_curso', nullif(btrim(coalesce(p_legajo,'')),''))
  returning id into v_id;
  perform public.gv_importados_resync(p_importado_id);
  return jsonb_build_object('bache_id', v_id, 'cod', r.cod_art, 'unidades', v_u);
end $$;

create or replace function public.gv_importado_bache_llego(p_bache_id bigint, p_unidades numeric default null, p_legajo text default null)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare b record; v_pend int; v_llego int; v_new int; v_estado text;
begin
  select * into b from public."GV_Importados_Baches" where id = p_bache_id;
  if not found then raise exception 'Bache % no existe', p_bache_id; end if;
  if b.estado <> 'en_curso' then raise exception 'El bache % no está en curso', p_bache_id; end if;
  v_pend := greatest(0, b.unidades - b.unidades_llegadas);
  v_llego := round(coalesce(p_unidades, v_pend));
  if v_llego <= 0 then raise exception 'unidades llegadas debe ser > 0'; end if;
  if v_llego > v_pend then v_llego := v_pend; end if;
  insert into public."Importados_Mov_Stock"(ts,cod_art,marca,tipo,delta_uni,ref,legajo,creado)
  values (now(), b.cod_art, b.marca, 'ingreso', v_llego, 'llegada bache importacion', nullif(btrim(coalesce(p_legajo,'')),''), now());
  v_new := b.unidades_llegadas + v_llego;
  v_estado := case when v_new >= b.unidades then 'llegado' else 'en_curso' end;
  update public."GV_Importados_Baches" set unidades_llegadas = v_new, estado = v_estado, actualizado = now() where id = p_bache_id;
  perform public.gv_importados_resync(b.importado_id);
  return jsonb_build_object('bache_id', p_bache_id, 'llego', v_llego, 'estado', v_estado);
end $$;

create or replace function public.gv_importado_bache_editar(p_bache_id bigint, p_unidades numeric default null, p_fecha date default null, p_set_fecha boolean default true)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare b record; v_u int;
begin
  select * into b from public."GV_Importados_Baches" where id = p_bache_id;
  if not found then raise exception 'Bache % no existe', p_bache_id; end if;
  if p_unidades is not null then
    v_u := round(p_unidades);
    if v_u < b.unidades_llegadas then raise exception 'unidades (%) no puede ser menor a lo ya llegado (%)', v_u, b.unidades_llegadas; end if;
    if v_u <= 0 then raise exception 'unidades debe ser > 0'; end if;
    update public."GV_Importados_Baches" set unidades = v_u,
           estado = case when v_u <= unidades_llegadas then 'llegado' else 'en_curso' end,
           actualizado = now() where id = p_bache_id;
  end if;
  if p_set_fecha then
    update public."GV_Importados_Baches" set fecha_reingreso = p_fecha, actualizado = now() where id = p_bache_id;
  end if;
  perform public.gv_importados_resync(b.importado_id);
  return jsonb_build_object('bache_id', p_bache_id);
end $$;

create or replace function public.gv_importado_bache_borrar(p_bache_id bigint)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare b record;
begin
  select * into b from public."GV_Importados_Baches" where id = p_bache_id;
  if not found then raise exception 'Bache % no existe', p_bache_id; end if;
  update public."GV_Importados_Baches" set estado = 'anulado', actualizado = now() where id = p_bache_id;
  perform public.gv_importados_resync(b.importado_id);
  return jsonb_build_object('bache_id', p_bache_id, 'estado', 'anulado');
end $$;

create or replace function public.gv_importado_baches(p_importado_id bigint)
returns table(id bigint, unidades int, unidades_llegadas int, pendiente int, fecha_reingreso date, estado text, creado timestamptz)
language sql stable security definer set search_path to 'public' as $$
  select id, unidades, unidades_llegadas, greatest(0, unidades - unidades_llegadas) as pendiente,
         fecha_reingreso, estado, creado
  from public."GV_Importados_Baches"
  where importado_id = p_importado_id and estado <> 'anulado'
  order by coalesce(fecha_reingreso, '9999-12-31'::date), id;
$$;

-- ROLLBACK (todo reversible):
--   restaurar mirrors:
--     update public."Importados" im set pedido_curso = b.pedido_curso, reingreso_est = b.reingreso_est
--     from public."GV_Importados_curso_bkp_20260911" b where b.id = im.id;
--   drop function gv_importado_baches(bigint), gv_importado_bache_borrar(bigint),
--        gv_importado_bache_editar(bigint,numeric,date,boolean), gv_importado_bache_llego(bigint,numeric,text),
--        gv_importado_bache_add(bigint,numeric,date,text), gv_importados_resync(bigint);
--   drop table public."GV_Importados_Baches";
--   y revertir el front (index.html: "Cargar pedido ya hecho" volvía a importados_set_curso + PATCH reingreso_est).
