-- v21.48 — El refresco del stock ENCADENA stocks_carga_rapida (Thomas, 2026-09-23)
--
-- Thomas, textual: "todo el stock tiene que verse lo mas en vivo posible siempre".
--
-- LO QUE SE MIDIO, Y ES LO QUE MOTIVA EL CAMBIO
-- =============================================
-- La pantalla de Stocks NO lee `vista_saldos_stock` ni la matview: lee la tabla
-- `stocks_carga_rapida`. O sea que el dato llega a la pantalla por TRES saltos:
--
--   Movimientos_Stock  -->  vista_stock_procesada  -->  stocks_carga_rapida  -->  pantalla
--     (el libro, vivo)      cron 55, */2, condicional   cron 57, */5, SIEMPRE
--
-- Atraso maximo: 2 + 5 = SIETE MINUTOS. Y los dos crons no estan sincronizados, asi
-- que si el 57 corre justo antes de que el 55 refresque, se pagan los 7 completos.
-- El cron 57, ademas, reescribe la tabla cada 5 min mire o no si algo cambio:
-- 580 corridas / 324 s / 559 ms en una ventana de 47,9 h, con el mismo 94,5 % de
-- corridas inutiles que ya se le habia sacado al 55 en la v21.06/v21.31.
--
-- EL CAMBIO: reescribirla en la MISMA corrida que refresca la matview.
--   * frescura: 7 min -> 2 min en la pantalla que mira el operario
--   * costo: el 57 deja de reescribirla cuando no cambio nada
--
-- (v19.53 ya habia sacado de `refresh_stocks_carga_rapida` su propio REFRESH de la
--  matview, justamente porque el cron 55 la refresca. Este cambio cierra esa cadena
--  desde el otro lado.)
--
-- LAS TRES DECISIONES QUE NO SON OBVIAS
-- =====================================
-- 1. TRY, no el lock bloqueante. El advisory 5768 lo comparten el cron 57 y el 68
--    (reconciliar-pipeline-stock, */10). Esperarlo ocuparia uno de los SEIS worker
--    slots de la instancia -- el pozo del apagon del 17/09 en LK. Si no se consigue,
--    no pasa nada: el cron 57 la reescribe en su proxima corrida.
-- 2. FAIL-OPEN, con el fallo A LA VISTA. Si la derivada explota, la matview se
--    refresca igual y el motivo lo dice. Probado rompiendo `refresh_stocks_carga_rapida`
--    a proposito (perform 1/0) en transaccion abortada:
--      refrescada=true | motivo=piso de frescura (60 min) (carga_rapida fallo: division by zero)
--    Tapar un error sin dejar como enterarse es cambiar un error ruidoso por uno mudo
--    (regla de Elias, v20.58).
-- 3. EL CRON 57 NO SE APAGA. Queda como red: es el que cubre el caso del lock ocupado
--    y el del fallo. Bajarlo a */10 es un segundo paso, y no esta hecho.
--
-- VERIFICACION (corrida de verdad, 23/09)
-- =======================================
--   solo_medir            -> refrescada=false, motivo='sin cambios'            (NO encadena)
--   piso de frescura en 0 -> refrescada=true,  motivo='... + carga_rapida'     3.260 ms
--   stocks_carga_rapida   -> 367 filas, md5 3000430e5cfbde71e8b995819a3ce21e
--                            IDENTICA antes y despues: el encadenado adelanta el
--                            dato, no lo cambia.
--   gv_reglas_perdidas    -> vacia
--
-- ROLLBACK (una linea, la definicion anterior esta en el backup):
--   select def from zz_backups."GV_Backup_funcdef_20260923"
--    where objeto = 'gv_refresh_stock_si_cambio(int,boolean)';
--   -- y se ejecuta ese texto tal cual.
--
-- OJO: traer SIEMPRE la definicion VIVA antes de tocar esta funcion
-- (select pg_get_functiondef('public.gv_refresh_stock_si_cambio(int, boolean)'::regprocedure);)
-- Varias sesiones tocan los objetos de stock al mismo tiempo.

-- ---------------------------------------------------------------------------
-- El bloque que se agrego, DENTRO de la rama que ya refrescaba:
-- ---------------------------------------------------------------------------
--   if v_do and not p_solo_medir then
--     refresh materialized view concurrently public.vista_stock_procesada;
--
--     begin
--       if pg_try_advisory_xact_lock(5768) then
--         perform public.refresh_stocks_carga_rapida();
--         v_cr := ' + carga_rapida';
--       else
--         v_cr := ' (carga_rapida: lock ocupado, la toma el cron 57)';
--       end if;
--     exception when others then
--       v_cr := ' (carga_rapida fallo: ' || left(sqlerrm, 60) || ')';
--     end;
--   end if;
--
-- y `v_cr` se concatena al motivo en los dos lugares donde se sella
-- (`ultimo_motivo` de GV_Stock_Refresh_Estado y el `motivo` que devuelve).

-- ---------------------------------------------------------------------------
-- Centinelas (es un insert, no codigo)
-- ---------------------------------------------------------------------------
insert into public."GV_Reglas_Centinela" (objeto, clase, patron, regla, quien_pidio, version)
values ('gv_refresh_stock_si_cambio', 'funcion', 'refresh_stocks_carga_rapida',
        'El refresco de la matview encadena la reescritura de stocks_carga_rapida en la MISMA corrida: la pantalla de Stocks lee esa tabla, no la matview, y sin el encadenado el dato le llega con hasta 7 min (2 del cron 55 + 5 del 57).',
        'Thomas', 'v21.48'),
       ('gv_refresh_stock_si_cambio', 'funcion', 'pg_try_advisory_xact_lock',
        'El encadenado toma el 5768 con TRY, nunca con el lock bloqueante: ese lock lo comparten el cron 57 y el 68, y esperarlo ocuparia uno de los SEIS worker slots de la instancia.',
        'Thomas', 'v21.48')
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- Chequeos
-- ---------------------------------------------------------------------------
-- select * from public.gv_reglas_perdidas;        -- vacia = todo bien
-- select * from public.gv_stock_refresh_salud;    -- ultimo_motivo tiene que decir '+ carga_rapida'
--                                                 -- cuando refresco; 'sin cambios' cuando salto.

-- ===========================================================================
-- v21.57 (Thomas, 23/09: "fijate que el 57 no lo este pisando") — EL DESFASE
-- ===========================================================================
--
-- LA CARRERA, MEDIDA (cron.job_run_details, 6 h):
-- Los tres arrancaban EN EL MISMO SEGUNDO, con decimas de diferencia:
--
--   minuto   cron 55            cron 57            cron 68
--   08:40    00.627 ·   417 ms  00.510 · 1.273 ms  00.773
--   08:30    00.620 · 4.264 ms  00.628 · 1.216 ms  00.748
--   08:10    00.308 · 3.799 ms  00.304 · 1.131 ms  00.475
--   08:00    00.929 · 1.187 ms  00.870 · 2.625 ms  01.102
--   07:00    00.523 · 1.178 ms  00.550 · 2.845 ms  00.891
--
-- `*/2` y `*/5` coinciden en los multiplos de 10: SEIS veces por hora.
--
-- Por que HOY solia ganar el dato bueno: el 57 termina en ~1,2 s y el refresco
-- del 55 tarda ~3,8 s, asi que el 57 libera el lock y el 55 encadena DESPUES,
-- con la matview ya nueva. Pero en 07:00 y 08:00 el 57 tardo 2,8 s y el 55
-- termino antes: ahi el 57 toma el lock primero, lee la matview VIEJA y el 55
-- se encuentra el lock ocupado y no corrige. `stocks_carga_rapida` queda con el
-- saldo viejo hasta la corrida siguiente.
--
-- ⚠ Y NO ES UN CASO TEORICO: `cron.job_run_details` tiene un
-- `job startup timeout` del PROPIO cron 68 el 22/09 a las 10:30 - uno de los mas
-- cargados. Esta instancia tiene `max_worker_processes = 6` (igual que LK), y
-- el minuto :00 junta 17 jobs.
--
-- EL ARREGLO: desfasarlos, sin tocar la funcion.
-- El 55 corre SOLO en minutos PARES (`*/2`). Mandando a los otros a IMPARES la
-- carrera desaparece, y el 55 dura 4,3 s en su peor caso: no cruza el minuto.
--
--   57: `*/5`  ->  `3-59/6`    (3,9,15,21,27,33,39,45,51,57)  cada 6 min
--   68: `*/10` ->  `1-59/10`   (1,11,21,31,41,51)
--
-- ⚠ CADA 6 Y CADA 10, NO CADA 5 NI CADA 15. La paridad se conserva solo si el
-- paso es PAR: `*/5` y `*/15` alternan par/impar por construccion, asi que un
-- cron cada 5 o cada 15 minutos NO PUEDE quedar siempre impar. Es la razon por
-- la que el 57 pasa de 5 a 6 minutos, y la razon por la que el 92 no se movio.
--
-- ⚠ EL LOCK 5768 LO TOMAN TRES JOBS, NO DOS: 57, 68 y **92**
-- (`gv-refrescar-articulo-empresa`, `*/15`). El 92 queda como esta —es cada 15,
-- no puede ser siempre impar— asi que sigue pisando al 55 en :00 y :30.
--
-- IMPACTO MEDIDO (minutos en que el 55 se encuentra el lock ocupado):
--   antes:   6 por hora  (57 y 68 en los multiplos de 10, + 92 en :00 y :30)
--   despues: 2 por hora  (solo el 92)
--   55 vs 57: 0     55 vs 68: 0     55 vs 92: 2  [:00, :30]
--
-- ⚠ El 57 y el 68 SIGUEN chocando entre si 2 veces por hora (:21 y :51), y es
-- inevitable: con paso 6 y paso 10 el mcm es 30. No molesta — el lock los
-- serializa y ninguno de los dos lee una matview a medio refrescar, porque el
-- 55 no corre en impares.
--
-- Y el pico por minuto BAJO: :00 paso de 19 jobs a 17, :30 de 17 a 15.
--
-- COSTO ACEPTADO: `fc_sin_salida` y las descripciones (que NO cuelgan de la
-- matview: salen de `vista_fc_sin_salida` y `vista_nombres_articulos`, vivas)
-- pasan de refrescarse cada 5 min a cada 6.
--
-- ROLLBACK, dos lineas:
--   select cron.alter_job(57, schedule := '*/5 * * * *');
--   select cron.alter_job(68, schedule := '*/10 * * * *');
