-- =====================================================================
-- insumos_factores.sql — v8.26
-- Factores de conversión por insumo: varias unidades que expresan el MISMO stock
-- (no se suman). La base la elige el insumo. factor = cuántas unidades BASE hay en 1
-- de esta unidad; la base tiene factor=1 y es_base=true.
--
-- Definición viva en la migración Supabase `insumos_factores_unidades`:
--   · tabla public."Insumos_Factores" (cod_art, unidad, factor>0, es_base, actualizado)
--     PK (cod_art, unidad). RLS: select con anon; sin insert/update/delete directo.
--   · RPC insumo_factores_guardar(p_cod text, p_factores jsonb) SECURITY DEFINER:
--     reemplaza TODO el set de factores del insumo. Valida exactamente 1 base.
--     grant execute a anon/authenticated (mismo patrón que insumo_cat/unidad_guardar).
--
-- Frontend (index.html, admin Insumos): _insFactores + insFetchFactores + helpers
-- (insAbase / insSaldoBase / insEquivStr) + editor ⚖ (stkInsEditFact/…FactGuardar) +
-- display de equivalencias en "Todos los insumos".
--
-- HECHO (Paso 2, v8.39): al GUARDAR cantidad, si el insumo tiene unidad base definida y la
-- unidad elegida tiene factor conocido, `_stkInsAjustar` (index.html) convierte la cantidad a
-- BASE (qNueva × factor) y registra el asiento en la unidad base. El ajuste se calcula contra el
-- saldo TOTAL en base (insSaldoBase), no contra xuni[0]. Sin factores → comportamiento clásico
-- (asiento en la unidad elegida). Append-only y stock-neutral. Cierra el anti-duplicado al cargar
-- en varias unidades.
-- =====================================================================
