-- =====================================================================
--  reconciliar_pipeline_stock.sql — Pipeline de stock SERVER-SIDE (v4.99)
--
--  PROBLEMA (root cause): "Pickeados" y "A facturar" mostraban 0 aunque
--  hubiera pedidos pickeados/armados, y la GÓNDOLA nunca bajaba por el picking.
--  TODO eso era UN SOLO bug:
--    • El CHECK `Movimientos_Stock_deposito_check` NO incluía
--      `separar_pedidos`, `a_facturar` ni `excedente` (solo a_guardar/
--      terminado/racks/insumos).
--    • El cliente `stockBajaPicking` arma el picking como UN batch
--      `stockMove([terminado−, separar_pedidos+])` → un solo POST a PostgREST.
--    • La fila `separar_pedidos` violaba el CHECK → PostgREST rechazaba TODO
--      el batch con HTTP 400.
--    • `stockMove` se TRAGA los 4xx (`if (r.ok || (status>=400 && <500)) return`)
--      → fallo silencioso: ni se descontaba góndola ni se llenaba separar.
--  Además los equipos de picking corren una app vieja (TWA) que ni siquiera
--  intentaba el pipeline.
--
--  FIX (este archivo / migraciones aplicadas):
--   1) `movimientos_stock_deposito_check_pipeline`: el CHECK ahora permite
--      terminado, excedente, separar_pedidos, a_facturar, a_guardar, racks, insumos.
--      (Desbloquea el pipeline tanto del cliente como del server.)
--   2) `reconciliar_pipeline_stock()` (migración `reconciliar_pipeline_stock`):
--      replica las etapas del cliente, pero del lado del server, idempotente:
--        ETAPA 1 (PKC/TP): separar_pedidos(+picked) y baja EXCEDENTE-FIRST
--          (excedente− y el resto góndola−). Dedup por índice único (ver v5.76).
--        ETAPA 2 (TAP):    mueve el neto de separar_pedidos → a_facturar.
--        ETAPA 3 (factura): saca de a_facturar cuando la tanda está 100%
--          facturada (todos los NP de la PPP en Facturacion_NP).
--        ETAPA 4 (CP):     saca de a_facturar las cajas 'cp' (Completar Pedido)
--          de una NP YA facturada — la ETAPA 3 no las ve porque el CP marca ref=NP
--          (sin tanda). Ver nota v6.69. (migración `pipeline_etapa4_drenar_cp_facturado`)
--      Dedup por la existencia del movimiento (separar_pedidos / tipo='separado'
--      / tipo='facturado' por ref=tanda). Comparte los `tipo` con el cliente, así
--      si una app nueva sí corre el pipeline, los guards evitan doble conteo.
--      Sólo procesa tandas con actividad POST-cutoff (Stock_Config.cutoff_ts);
--      lo anterior ya está en el snapshot `inicial`. SECURITY DEFINER, revoke
--      anon/authenticated, grant service_role. Nunca lanza (devuelve texto).
--
--  CRON: jobid 22 `reconciliar-pipeline-stock`, `*/10 * * * *` (cada 10 min).
--    select cron.schedule('reconciliar-pipeline-stock','*/10 * * * *',
--      $$select public.reconciliar_pipeline_stock();$$);
--    (Registros_Produccion_Virgilio es chico → el scan cada 10 min es trivial.)
--    Mantiene Pickeados/A facturar al día desde los eventos sin depender de la
--    app vieja. El pipeline del cliente queda como "fast path" (instantáneo); el
--    cron es la red de seguridad para equipos con app vieja.
--
--  v5.76 — EL CRON ES EL ÚNICO ESCRITOR DEL PICKING. El "fast path" del cliente
--    (stockBajaPicking, TP) se DESACTIVÓ: el guard chequear-y-después-insertar no
--    es atómico y la cola offline del cliente (vir_stock_pend) abría una ventana en
--    la que el cron insertaba primero y el cliente duplicaba (separar +2×, góndola
--    −2×; se vio en C81B/C87A/C87F/C87H, ~486 cajas). Ahora el cliente NO toca el
--    stock del picking (solo emite el aviso SSG). Se limpiaron a mano las filas de
--    picking del cliente en esas 4 tandas (C81B/C87A ya facturadas → además ajuste
--    compensatorio en separar_pedidos, tipo='ajuste_doble_pipeline').
--    v5.76 (2ª parte) — DEDUP ATÓMICO + EXCEDENTE-FIRST:
--     (a) EXCEDENTE-FIRST portado a ETAPA 1: se baja primero de excedente y el resto
--         de góndola (window por artículo para no sobre-descontar el excedente si
--         dos tandas del mismo art entran en la misma corrida). No se pierde la
--         lógica que tenía el cliente.
--     (b) Índice único parcial `mov_stock_pipeline_dedup` UNIQUE
--         (upper(trim(ref)), upper(trim(cod_art)), deposito, tipo)
--         WHERE tipo IN ('picking','separado','facturado') → una sola fila por
--         (tanda, art, depósito, etapa). Mata la race para las 3 etapas a nivel DB.
--         Las 3 etapas del cron usan ON CONFLICT DO NOTHING; el cliente (que aún
--         escribe separado/facturado hasta el merge) choca y su 4xx se traga solo.
--         tipo va EN la clave porque en separar_pedidos conviven picking(+) y
--         separado(−).
--
--  BACKLOG RECONCILIADO (29/06): 6 tandas en vuelo, post-cutoff:
--    separar_pedidos (Pickeados) = 627  → C58C 108 + C58E 44 + C59C 475
--    a_facturar      (A facturar) = 442 → C58A 115 + C58B 247 + C58D 80
--    góndola: −634 sólo de las 3 sin descuento previo (C58A/C58E/C59C);
--             C58B/C58C/C58D ya tenían el descuento del seed manual.
--    Góndola quedó con sólo 2 artículos en −5 (despreciable).
--
--  v6.29 — FIX DOBLE-FACTURADO (a_facturar negativo). La ETAPA 3 agrupaba por
--    `ref` crudo y solo deduplicaba contra `facturado ref=tanda`. Pero el CLIENTE
--    factura por NP con `ref=tanda|NP` → el cron NO lo veía y volvía a facturar
--    (`ref=tanda`) → DOBLE facturado → a_facturar quedaba NEGATIVO (restaba stock
--    real del total). Se veía en 137 códigos / 364 tandas / 1.417 cajas, 100%
--    explicado por este pipeline. Fix (migración `pipeline_etapa3_facturado_por_
--    tanda_evita_doble`): la ETAPA 3 ahora calcula el neto y el dedup POR TANDA,
--    contando también los facturados del cliente (`ref=tanda|NP` → normaliza con
--    split_part(ref,'|',1)). Solo drena el remanente REAL: si el cliente ya lo
--    sacó, net<=0 y no hace nada → nunca más duplica. Los 1.417 ya colgados se
--    compensaron con ajustes trazables (tipo='ajuste', legajo='reconcilia', uno
--    por tanda, llevando cada a_facturar-por-tanda a 0). ETAPA 1 y 2 sin cambios.
--
--  v6.69 — ETAPA 4: DRENAR CAJAS DE "COMPLETAR PEDIDO" (CP) DE NPs YA FACTURADAS.
--    Root cause: un CP que completa una NP **ya facturada** mete cajas en a_facturar
--    con `tipo='cp'` y `ref=NP` (solo el número, sin tanda). El fast-path del cliente
--    (`stockDrenarCPFacturado`, llamado en cpConfirm y en el tilde de Facturación) debía
--    sacarlas, pero es best-effort y falló en varios casos reales (p.ej. NP 98017 art
--    534 +1, y 12 NPs más — ~202 cajas). El cron NO las veía: la ETAPA 3 agrupa por
--    TANDA y solo mira `tipo in ('separado','facturado')`. Quedaban colgadas inflando
--    a_facturar (había que limpiarlas a mano, como el 280 de la 98017).
--    FIX (migración `pipeline_etapa4_drenar_cp_facturado`): la ETAPA 4 netea el bucket
--    "por NP" = todas las filas de a_facturar cuyo `split_part(ref,'|',1)` es el número
--    de NP, sumando SOLO `tipo in ('cp','facturado','ajuste')` (se EXCLUYEN `rc` y
--    `separado` para no interferir con esos mecanismos). Si el neto es >0 y la NP está
--    en `Facturacion_NP` (ya facturada), inserta un `facturado` −neto con `ref=NP|CP`,
--    `ubicacion='__cp__'`, `legajo='pipeline'` — MISMO formato que el fast-path del
--    cliente, así ambos deduplican entre sí. Idempotente: el net>0 lo lleva a 0 (segunda
--    corrida drena 0) + el índice único `mov_stock_pipeline_dedup`. **Trata el legajo 0
--    como REAL** (un CP de admin/sistema mueve stock real): no filtra por legajo. Las NPs
--    aún NO facturadas (ej. 44500) quedan intactas: drenan cuando se facturen. El `return`
--    ahora incluye `etapa4=N`. Backlog: al aplicar la migración se corrió una vez a mano
--    → drenó los 13 casos colgados (incluido el 534).
--
--  v9.26 — ETAPA 3 FUENTE DURABLE (fix pedidos Chef que rompían stock).
--    Root cause: la ETAPA 3 drenaba `a_facturar` SOLO si la tanda seguía en
--    `PPP_Programacion_Diaria` (el PPP del día, que se reemplaza a diario). Los
--    pedidos de CHEF (44xxx, que facturan mercadería LK afuera de la app) se
--    facturan DESPUÉS de que la tanda se cae del PPP → la condición `exists(PPP...)`
--    daba falso → NUNCA drenaba → el stock LK quedaba trabado en a_facturar (fantasma
--    que rompe stocks). Caso testigo: tanda D15A (NPs 44531/44532/44533), 550 cajas
--    colgadas desde el 05/08. Fix: ETAPA 3 usa una CTE `tandanp` = NPs de la tanda de
--    `PPP_Entregados_Meta` (histórico, durable) ∪ `PPP_Programacion_Diaria` (actual),
--    en vez de solo el PPP del día. Así drena cuando TODAS las NP de la tanda están en
--    `Facturacion_NP`, tenga o no la tanda en el PPP. Los guards anti-doble se mantienen
--    (`not exists facturado` por tanda + índice único). Backlog colgado (D15A 550 +
--    D06E 3 = 553 cajas) se drenó a mano con `facturado`/`legajo='reconcilia'`,
--    `ref='<tanda>|FIX_CHEF_ESTANCADO_20260811'` (trazable/reversible). Verificado: sin
--    a_facturar negativos.
--
--  v11.73 — FIX EXCEDENTE NEGATIVO POR DRIFT ACUMULATIVO (B.2 DO NOTHING → DO UPDATE).
--    Root cause: la sección B.2 de ETAPA 1 insertaba la fila de excedente con
--    `ON CONFLICT DO NOTHING`. Al cambiar el excedente disponible entre corridas
--    (nuevas MGs, nuevos pickings de otros artículos), la window function
--    `exc_avail − sum(picked) OVER ...` recalculaba `from_exc` pero la fila ya
--    existente en Movimientos_Stock NO se actualizaba → cada corrida sobre-asignaba
--    excedente respecto al stock real → drift acumulativo → saldo excedente NEGATIVO.
--    Caso testigo: art 546, excedente llegó a -4 (63 filas de picking acumularon
--    drift). Fix: B.2 cambia de `DO NOTHING` a `DO UPDATE SET delta = excluded.delta,
--    legajo = excluded.legajo` — la misma semántica que B.1 (separar_pedidos) y B.3
--    (terminado), que ya eran UPSERT. El próximo cron recalcula TODAS las filas de
--    excedente con el from_exc correcto y se auto-sana.
--    Secciones A y B.1/B.3 sin cambios.
--
--  v11.72 — LEGAJO REAL EN ETAPA 1 Y 2 (fix "legajo pipeline").
--    Root cause: las etapas 1 y 2 hardcodeaban `'pipeline'` como legajo en TODOS
--    los Movimientos_Stock que creaban. El operario que realmente pickeó/armó
--    quedaba invisible en la trazabilidad — y las alertas de stock negativo decían
--    "legajo pipeline" en vez de mostrar quién fue.
--    FIX: ETAPA 1 (`reconciliar_pipeline_stock_etapa1`) ahora extrae el legajo
--    real del PKC (último registro PKC de la tanda, por `ts_cliente DESC`) usando
--    `(array_agg(r.legajo::text ORDER BY r.ts_cliente DESC NULLS LAST))[1]`.
--    Aplica a ambas secciones A (histórico) y B (forward). Fallback a 'pipeline'
--    si no hay legajo.
--    ETAPA 2 (`reconciliar_pipeline_stock_etapa2`) ahora extrae el legajo real
--    del TAP (último registro TAP de la tanda) con la misma mecánica. Se agrega
--    CTE `tap_leg` y se joinea en `alloc`. Fallback a 'pipeline'.
--    ETAPA 3 y 4 mantienen 'pipeline': el actor es el sistema/facturación, no un
--    operario específico.
--    Funciones fuente: `sql/reconciliar_pipeline_stock_etapa1.sql` y
--    `sql/reconciliar_pipeline_stock_etapa2.sql`.
--
--  La definición viva de la función está en la migración homónima en Supabase.
--  Este archivo es la documentación del diseño (convención de sql/).
-- =====================================================================
