-- ============================================================
--  sync_precios_venta — cron que refresca precios_venta + cob_uxb_lk
--  desde LK + Chef vía la Edge Function sync-precios-venta.
--  Proyecto Supabase: Control Partes Talleristas (hrxfctzncixxqmpfhskv)
--
--  PATRÓN: idéntico a sync-clientes-dto-14d. pg_cron llama a la Edge
--  Function por net.http_post; la función lee products + loke_products
--  de LK via REST (WEB_SERVICE_KEY) y products de Chef via REST
--  (CHEF_KEY — publishable key) y hace upsert en Virgilio.
--
--  FRECUENCIA: diaria a las 06:00 ART (09:00 UTC). Los precios cambian
--  con poca frecuencia (actualizaciones de lista); una vez por día es
--  más que suficiente y alinea con los otros syncs matutinos.
--
--  CONDICIÓN: solo dispara si el dato tiene más de 24 h de antigüedad
--  (max(actualizado) < now() - interval '24 hours'), para no gastar un
--  invocación si ya se sincronizó hoy por otro camino.
--
--  TABLAS DESTINO:
--    precios_venta     — cod, precio_unit, uxb, descripcion (de LK + Chef products)
--    cob_uxb_lk        — cod, uxb (de products ∪ loke_products)
--
--  FUENTES:
--    LK  (kwkclwhmoygunqmlegrg) → products, loke_products (WEB_SERVICE_KEY)
--    Chef (nkhzocgdpwtgrmwleihr) → products (CHEF_KEY, publishable key)
--    LK y Chef tienen catálogos separados (rangos de código distintos).
--    Si coincide un código, Chef gana (catálogo más reciente).
--
--  WATCHDOG: agregar el jobid al VALUES de watchdog_syncs_externos()
--  con umbral de 2880 min (48 h, ~2x el período de 24 h).
-- ============================================================

-- La Edge Function se deploya manualmente (Dashboard o MCP).
-- Nombre: sync-precios-venta, verify_jwt: OFF.
-- Deployada: 2026-08-31 (con soporte LK + Chef).

-- Cron job (jobid 66, creado 2026-08-31):
-- select cron.schedule(
--   'sync-precios-venta',
--   '0 9 * * *',          -- 09:00 UTC = 06:00 ART
--   $body$
--   do $inner$
--   begin
--     if (select max(actualizado) from public.precios_venta) > now() - interval '24 hours' then
--       raise notice 'sync-precios-venta: dato fresco (< 24 h), salteado';
--       return;
--     end if;
--     perform net.http_post(
--       url     := 'https://hrxfctzncixxqmpfhskv.supabase.co/functions/v1/sync-precios-venta',
--       headers := '{"Content-Type":"application/json"}'::jsonb,
--       body    := '{}'::jsonb
--     );
--   end $inner$;
--   $body$
-- );
--
-- Para ver el jobid asignado:
--   select jobid, jobname from cron.job where jobname = 'sync-precios-venta';
--
-- Agregar al watchdog (reemplazar NN por el jobid real):
--   Sumar (NN, 2880) al VALUES de watchdog_syncs_externos().
--
-- Rollback:
--   select cron.unschedule('sync-precios-venta');

-- ============================================================
--  Verificación post-deploy
-- ============================================================
-- 1. Invocar a mano:
--    select net.http_post(
--      url := 'https://hrxfctzncixxqmpfhskv.supabase.co/functions/v1/sync-precios-venta',
--      headers := '{"Content-Type":"application/json"}'::jsonb,
--      body := '{}'::jsonb
--    );
-- 2. Esperar ~5 seg y chequear:
--    select count(*), max(actualizado) from public.precios_venta;
--    select count(*) from public.cob_uxb_lk;
-- 3. Comparar contra LK (correr en el SQL Editor de LK):
--    select count(*) from products where coalesce(list_price,0) > 0 and btrim(coalesce(cod,'')) <> '';
-- 4. Los conteos deben coincidir (± productos con cod vacío o list_price = 0).
-- 5. Resultado esperado: ~319 precios (221 LK + 101 Chef, ~3 overlaps).
