-- ============================================================
--  sync_precios_venta — cron que refresca precios_venta + precios_venta_chef
--  + cob_uxb_lk desde LK + Chef vía la Edge Function sync-precios-venta.
--  Proyecto Supabase: Control Partes Talleristas (hrxfctzncixxqmpfhskv)
--
--  PATRÓN: idéntico a sync-clientes-dto-14d. pg_cron llama a la Edge
--  Function por net.http_post; la función lee products + loke_products
--  de LK via REST (WEB_SERVICE_KEY) y products de Chef via REST
--  (CHEF_KEY — publishable key) y hace upsert en Virgilio.
--
--  FRECUENCIA (v14.45, 2026-09-08): cada 15 min (*/15 * * * *). Pedido del
--  dueño: que un cambio de precio en LK/Chef se refleje casi en vivo (lag
--  máximo 15 min) sin poner un trigger en los proyectos de las páginas. La
--  función es idempotente y liviana (~330 LK + ~100 Chef), correrla seguido
--  no molesta. Antes era diaria a las 06:00 ART con guarda de 24 h; la guarda
--  se sacó (si no, saltearía todas las corridas del día menos la primera).
--
--  TABLAS DESTINO (v14.44 — listas SEPARADAS por empresa):
--    precios_venta      — cod, precio_unit, uxb, descripcion (SÓLO LK products)
--    precios_venta_chef — cod, precio_unit, uxb, descripcion (SÓLO Chef products)
--    cob_uxb_lk         — cod, uxb (de products ∪ loke_products de LK)
--
--  FUENTES:
--    LK  (kwkclwhmoygunqmlegrg) → products, loke_products (WEB_SERVICE_KEY)
--    Chef (nkhzocgdpwtgrmwleihr) → products (CHEF_KEY, publishable key)
--    LK y Chef son DOS listas separadas (v14.44). Antes se mergeaban en
--    precios_venta con "Chef gana", lo que ensuciaba las NP de LK con códigos
--    compartidos (809E). La valuación se enruta por empresa (ver §3.bi).
--
--  WATCHDOG: agregar el jobid al VALUES de watchdog_syncs_externos()
--  con umbral holgado (p.ej. 120 min, ~8x el período de 15 min).
-- ============================================================

-- La Edge Function se deploya manualmente (Dashboard o MCP).
-- Nombre: sync-precios-venta, verify_jwt: OFF.
-- Deployada: 2026-08-31 (con soporte LK + Chef).

-- Cron job (jobid 66, creado 2026-08-31; frecuencia bajada a 15 min v14.45 2026-09-08):
-- select cron.alter_job(
--   66,
--   schedule := '*/15 * * * *',
--   command  := $body$
--   select net.http_post(
--     url     := 'https://hrxfctzncixxqmpfhskv.supabase.co/functions/v1/sync-precios-venta',
--     headers := '{"Content-Type":"application/json"}'::jsonb,
--     body    := '{}'::jsonb
--   );
--   $body$
-- );
-- Para volver a diario con guarda de 24 h: cron.alter_job(66, schedule := '0 9 * * *',
--   command := <bloque do/begin con el if max(actualizado) > now()-24h return>).
--
-- Para ver el jobid asignado:
--   select jobid, jobname from cron.job where jobname = 'sync-precios-venta';
--
-- Agregar al watchdog (reemplazar NN por el jobid real):
--   Sumar (NN, 2880) al VALUES de watchdog_syncs_externos().
--
-- Rollback:
--   select cron.unschedule('sync-precios-venta');

-- ============================================================
--  Verificación post-deploy
-- ============================================================
-- 1. Invocar a mano:
--    select net.http_post(
--      url := 'https://hrxfctzncixxqmpfhskv.supabase.co/functions/v1/sync-precios-venta',
--      headers := '{"Content-Type":"application/json"}'::jsonb,
--      body := '{}'::jsonb
--    );
-- 2. Esperar ~5 seg y chequear:
--    select count(*), max(actualizado) from public.precios_venta;
--    select count(*) from public.cob_uxb_lk;
-- 3. Comparar contra LK (correr en el SQL Editor de LK):
--    select count(*) from products where coalesce(list_price,0) > 0 and btrim(coalesce(cod,'')) <> '';
-- 4. Los conteos deben coincidir (± productos con cod vacío o list_price = 0).
-- 5. Resultado esperado: ~319 precios (221 LK + 101 Chef, ~3 overlaps).
